--------------------------------------------- Project 1317 Cohort Creation Part Four Script - 17/12/2021 --------------------------------------------------


-------BMI CODE COUNTS------------------------------------------------------------------------------------------------------------------------------------
-- COUNTS OF EACH BMI CODE (events) - ADULT ASTHMA 

DECLARE GLOBAL TEMPORARY TABLE BMI AS (
SELECT COUNT(wgec.ALF_PE) AS Patient_Count, CATEGORY, wgec.EVENT_CD, TERM 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY saa ON wgec.ALF_PE = saa.ALF_PE 
INNER JOIN SAILW1317V.CM_BMI bmi ON bmi.EVENT_CD = wgec.EVENT_CD 
WHERE wgec.ALF_PE = saa.ALF_PE 
GROUP BY wgec.EVENT_CD, TERM, CATEGORY
ORDER BY wgec.EVENT_CD, TERM, CATEGORY 
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

CREATE TABLE sailw1317v.BMI_EVENTS_1(
Patient_Count INT, CATEGORY VARCHAR(100), EVENT_CD VARCHAR(100), TERM VARCHAR(100)
)

INSERT INTO  sailw1317v.BMI_EVENTS_1
SELECT Patient_Count, CATEGORY, EVENT_CD, TERM 
FROM SESSION.BMI

SELECT * FROM sailw1317v.BMI_EVENTS_1

-- COUNTS OF EACH BMI CODE (PEOPLE) - ADULT ASTHMA 
DECLARE GLOBAL TEMPORARY TABLE BMI2 AS (
SELECT COUNT(DiSTINCT wgec.ALF_PE) AS Patient_Count, CATEGORY, wgec.EVENT_CD, TERM 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY saa ON wgec.ALF_PE = saa.ALF_PE 
INNER JOIN SAILW1317V.CM_BMI bmi ON bmi.EVENT_CD = wgec.EVENT_CD 
WHERE wgec.ALF_PE = saa.ALF_PE 
GROUP BY wgec.EVENT_CD, TERM, CATEGORY
ORDER BY wgec.EVENT_CD, TERM, CATEGORY 
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

CREATE TABLE sailw1317v.BMI_1(
Patient_Count INT, CATEGORY VARCHAR(100), EVENT_CD VARCHAR(100), TERM VARCHAR(100)
)

INSERT INTO  sailw1317v.BMI_1
SELECT Patient_Count, CATEGORY, EVENT_CD, TERM 
FROM SESSION.BMI2

SELECT * FROM sailw1317v.BMI_1

-- COUNTS OF EACH BMI CODE (events) - CHILD ASTHMA 

DECLARE GLOBAL TEMPORARY TABLE CA_BMI AS (
SELECT COUNT(wgec.ALF_PE) AS Patient_Count, CATEGORY, wgec.EVENT_CD, TERM 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec
INNER JOIN sailw1317v.SS_ASTHMA_CHILD_COMORBIDITY saa ON wgec.ALF_PE = saa.ALF_PE 
INNER JOIN SAILW1317V.CM_BMI bmi ON bmi.EVENT_CD = wgec.EVENT_CD 
WHERE wgec.ALF_PE = saa.ALF_PE 
GROUP BY wgec.EVENT_CD, TERM, CATEGORY
ORDER BY wgec.EVENT_CD, TERM, CATEGORY 
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

CREATE TABLE sailw1317v.BMI_EVENTS_2(
Patient_Count INT, CATEGORY VARCHAR(100), EVENT_CD VARCHAR(100), TERM VARCHAR(100)
)

INSERT INTO  sailw1317v.BMI_EVENTS_2
SELECT Patient_Count, CATEGORY, EVENT_CD, TERM 
FROM SESSION.CA_BMI

SELECT * FROM sailw1317v.BMI_EVENTS_2

-- COUNTS OF EACH BMI CODE (PEOPLE) - CHLD ASTHMA 
DECLARE GLOBAL TEMPORARY TABLE CA_BMI2 AS (
SELECT COUNT(DiSTINCT wgec.ALF_PE) AS Patient_Count, CATEGORY, wgec.EVENT_CD, TERM 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec
INNER JOIN sailw1317v.SS_ASTHMA_CHILD_COMORBIDITY saa ON wgec.ALF_PE = saa.ALF_PE 
INNER JOIN SAILW1317V.CM_BMI bmi ON bmi.EVENT_CD = wgec.EVENT_CD 
WHERE wgec.ALF_PE = saa.ALF_PE 
GROUP BY wgec.EVENT_CD, TERM, CATEGORY
ORDER BY wgec.EVENT_CD, TERM, CATEGORY 
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

CREATE TABLE sailw1317v.BMI_2(
Patient_Count INT, CATEGORY VARCHAR(100), EVENT_CD VARCHAR(100), TERM VARCHAR(100)
)

INSERT INTO  sailw1317v.BMI_2
SELECT Patient_Count, CATEGORY, EVENT_CD, TERM 
FROM SESSION.CA_BMI2

SELECT * FROM sailw1317v.BMI_2

-- COUNTS OF EACH BMI CODE (events) - COPD 

DECLARE GLOBAL TEMPORARY TABLE COPD_BMI AS (
SELECT COUNT(wgec.ALF_PE) AS Patient_Count, CATEGORY, wgec.EVENT_CD, TERM 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec
INNER JOIN sailw1317v.SS_COPD_COMORBIDITY saa ON wgec.ALF_PE = saa.ALF_PE 
INNER JOIN SAILW1317V.CM_BMI bmi ON bmi.EVENT_CD = wgec.EVENT_CD 
WHERE wgec.ALF_PE = saa.ALF_PE 
GROUP BY wgec.EVENT_CD, TERM, CATEGORY
ORDER BY wgec.EVENT_CD, TERM, CATEGORY 
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

CREATE TABLE sailw1317v.BMI_EVENTS_3(
Patient_Count INT, CATEGORY VARCHAR(100), EVENT_CD VARCHAR(100), TERM VARCHAR(100)
)

INSERT INTO  sailw1317v.BMI_EVENTS_3
SELECT Patient_Count, CATEGORY, EVENT_CD, TERM 
FROM SESSION.COPD_BMI

SELECT * FROM sailw1317v.BMI_EVENTS_3

-- COUNTS OF EACH BMI CODE (PEOPLE) - COPD
DECLARE GLOBAL TEMPORARY TABLE COPD_BMI2 AS (
SELECT COUNT(DiSTINCT wgec.ALF_PE) AS Patient_Count, CATEGORY, wgec.EVENT_CD, TERM 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec
INNER JOIN sailw1317v.SS_COPD_COMORBIDITY saa ON wgec.ALF_PE = saa.ALF_PE 
INNER JOIN SAILW1317V.CM_BMI bmi ON bmi.EVENT_CD = wgec.EVENT_CD 
WHERE wgec.ALF_PE = saa.ALF_PE 
GROUP BY wgec.EVENT_CD, TERM, CATEGORY
ORDER BY wgec.EVENT_CD, TERM, CATEGORY 
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

CREATE TABLE sailw1317v.BMI_3(
Patient_Count INT, CATEGORY VARCHAR(100), EVENT_CD VARCHAR(100), TERM VARCHAR(100)
)

INSERT INTO  sailw1317v.BMI_3
SELECT Patient_Count, CATEGORY, EVENT_CD, TERM 
FROM SESSION.COPD_BMI2

SELECT * FROM sailw1317v.BMI_3

-- CODE 22k.. FLAG

DECLARE GLOBAL TEMPORARY TABLE COD22K_Events_Asthma AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, wgec.EVENT_VAL
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = '22K..'
AND wgec.EVENT_DT > '01/04/2020' 
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE COD22K_Events_COPD AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, wgec.EVENT_VAL
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.SS_COPD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = '22K..'
AND wgec.EVENT_DT > '01/04/2020' 
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE COD22K_FLAG_ASTHMA AS (
SELECT saa.*
, CASE WHEN  saa.ALF_PE IN (SELECT ALF_PE FROM SESSION.COD22K_Events_Asthma WHERE EVENT_CD = '22K..' AND EVENT_VAL >= '30') THEN 1 ELSE 0 END AS COD22K_FLAG
FROM sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY saa
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE COD22K_FLAG_COPD AS (
SELECT saa.*
, CASE WHEN  saa.ALF_PE IN (SELECT ALF_PE FROM SESSION.COD22K_Events_COPD WHERE EVENT_CD = '22K..' AND EVENT_VAL >= '30') THEN 1 ELSE 0 END AS COD22K_FLAG
FROM sailw1317v.SS_COPD_COMORBIDITY saa
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS 

-- DROP TABLES FOR CHANGES 


-- CREATE TABLE FOR ASTHMA
CREATE TABLE sailw1317v.SS_COD22K_FLAG_ASTHMA
(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
,COD22K_FLAG INT)

INSERT INTO  sailw1317v.SS_COD22K_FLAG_ASTHMA
SELECT TABLE_ID 
,ALF_PE  
,WOB
,AGE_AT_END_OF_FOLLOW_UP  
,FIRST_EVENT
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, COD22K_FLAG
FROM SESSION.COD22K_FLAG_ASTHMA

-- CREATE TABLE FOR COPD
CREATE TABLE sailw1317v.SS_COD22K_FLAG_COPD
(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
,COD22K_FLAG INT)

INSERT INTO sailw1317v.SS_COD22K_FLAG_COPD
SELECT TABLE_ID 
,ALF_PE  
,WOB
,AGE_AT_END_OF_FOLLOW_UP  
,FIRST_EVENT
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, COD22K_FLAG
FROM SESSION.COD22K_FLAG_COPD

SELECT * FROM sailw1317v.SS_COD22K_FLAG_ASTHMA
ORDER BY ALF_PE

SELECT * FROM sailw1317v.SS_COD22K_FLAG_COPD
ORDER BY ALF_PE


---- GRAND COHORT ONE - ADULTS ----------------------------------------------------------------------------------------------------------------------------

-- Filter Spirometry Values
DECLARE GLOBAL TEMPORARY TABLE ALL_EVENTS_LESS_THAN_1 AS (
SELECT DISTINCT wgec.ALF_PE, wgec.EVENT_CD, wgec.EVENT_DT, wgec.EVENT_VAL FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ26_SPIROMETRY  AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD IN( '3398.', '3399.', '339M.', '339O1', '339R.', '339T.', '339U.', '339j.', '339k.', '339l.', '339m.', '339r.') AND wgec.EVENT_VAL <= 1
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;
 
DECLARE GLOBAL TEMPORARY TABLE ALL_EVENTS_OVER_1 AS (
SELECT DISTINCT wgec.ALF_PE, wgec.EVENT_CD, wgec.EVENT_DT, wgec.EVENT_VAL AS PERCENTAGE FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ26_SPIROMETRY  AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD IN( '3398.', '3399.', '339M.', '339O1', '339R.', '339T.', '339U.', '339j.', '339k.', '339l.', '339m.', '339r.') AND wgec.EVENT_VAL >= 1
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

UPDATE SESSION.ALL_EVENTS_OVER_1 SET PERCENTAGE = PERCENTAGE/100

DECLARE GLOBAL TEMPORARY TABLE ALL_OTHER_SPIROMETRY_EVENTS AS (
SELECT DISTINCT wgec.ALF_PE, wgec.EVENT_CD, wgec.EVENT_DT, wgec.EVENT_VAL FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ26_SPIROMETRY  AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD NOT IN( '3398.', '3399.', '339M.', '339O1', '339R.', '339T.', '339U.', '339j.', '339k.', '339l.', '339m.', '339r.')
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.ALL_OTHER_SPIROMETRY_EVENTS 

DECLARE GLOBAL TEMPORARY TABLE SPIROMETRY_CORRECTED AS( 
SELECT ALF_PE, EVENT_CD, EVENT_DT, EVENT_VAL FROM 
(
SELECT ALF_PE, EVENT_CD, EVENT_DT, EVENT_VAL FROM SESSION.ALL_EVENTS_LESS_THAN_1 
UNION ALL
SELECT ALF_PE, EVENT_CD, EVENT_DT, PERCENTAGE FROM SESSION.ALL_EVENTS_OVER_1
)
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DELETE FROM SESSION.SPIROMETRY_CORRECTED WHERE EVENT_VAL > 1 

DELETE FROM SESSION.SPIROMETRY_CORRECTED WHERE EVENT_VAL < 0.2

DECLARE GLOBAL TEMPORARY TABLE SPIROMETRY_CORRECTED_2 AS( 
SELECT ALF_PE, EVENT_CD, EVENT_DT, EVENT_VAL FROM 
(
SELECT ALF_PE, EVENT_CD, EVENT_DT, EVENT_VAL FROM SESSION.SPIROMETRY_CORRECTED 
UNION ALL
SELECT ALF_PE, EVENT_CD, EVENT_DT, EVENT_VAL FROM SESSION.ALL_OTHER_SPIROMETRY_EVENTS
)
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.SPIROMETRY_CORRECTED_2 

---2.3 any objective measurement (at least one of peak flow, FeNO, or spirometry)
DECLARE GLOBAL TEMPORARY TABLE Q23 AS (
  SELECT  'PEAK_FLOW' AS EVENT_CAT, EVENT_CD, TERM FROM sailw1317v.AQ24_PEAK_FLOW apf  
  UNION ALL
  SELECT  'FENO' AS EVENT_CAT, EVENT_CD, TERM FROM sailw1317v.AQ25_FENO 
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE Cohort_Q23_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.EVENT_CAT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SESSION.Q23 AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD 
AND wgec.EVENT_DT > '01/04/2020' 
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC1_Q23 AS (
SELECT saa.* 
, CASE WHEN saa.ALF_PE IN (SELECT ALF_PE FROM SESSION.Cohort_Q23_Events WHERE EVENT_CAT = 'PEAK_FLOW' ) THEN 1 ELSE 0 END AS PEAK_FLOW_FLAG
, CASE WHEN saa.ALF_PE IN (SELECT ALF_PE FROM SESSION.SPIROMETRY_CORRECTED_2) THEN 1 ELSE 0 END AS SPIROMETRY_FLAG
, CASE WHEN saa.ALF_PE IN (SELECT ALF_PE FROM SESSION.Cohort_Q23_Events WHERE EVENT_CAT = 'FENO' ) THEN 1 ELSE 0 END AS FENO_FLAG
FROM sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY saa
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC1_Q23 ORDER BY ALF_PE

-- DROP TABLE FOR ALTERATIONS 
DROP TABLE sailw1317v.SS_GC1_Q23

--CREATE PERMINENT TABLE
CREATE TABLE sailw1317v.SS_GC1_Q23
(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, PEAK_FLOW_FLAG INT
, SPIROMETRY_FLAG INT
, FENO_FLAG INT)

INSERT INTO  sailw1317v.SS_GC1_Q23
SELECT TABLE_ID 
,ALF_PE  
,WOB
,AGE_AT_END_OF_FOLLOW_UP  
,FIRST_EVENT
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, ANXIETY_SCREENING_FLAG
, PEAK_FLOW_FLAG 
, SPIROMETRY_FLAG 
, FENO_FLAG 
FROM SESSION.GC1_Q23

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC1_Q23

--2.4 Peak flow (required for all time (ever) and in the past 2 years only)
--No peak flow codes ever/past 2 years
--Peak flow 339A. or 339B. codes ever/past 2 years
--Peak flow diary ever/past 2 years (66YY – should be labelled in codelist)
--Any peak flow test ever/past 2 years

DECLARE GLOBAL TEMPORARY TABLE Cohort_Q24_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.EVENT_CAT, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SESSION.Q23 AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD 
AND EVENT_CAT = 'PEAK_FLOW'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;


DECLARE GLOBAL TEMPORARY TABLE GC1_Q24 AS (
SELECT saa.*
, CASE WHEN  saa.ALF_PE IN (SELECT ALF_PE FROM SESSION.Cohort_Q24_Events WHERE EVENT_CAT = 'PEAK_FLOW' ) THEN 1 ELSE 0 END AS PEAK_FLOW_FLAG
, CASE WHEN  saa.ALF_PE IN (SELECT ALF_PE FROM SESSION.Cohort_Q24_Events WHERE EVENT_CAT = 'PEAK_FLOW' AND EVENT_DT > '2020-11-01') THEN 1 ELSE 0 END AS PEAK_FLOW_FLAG_2_YEARS
, CASE WHEN  saa.ALF_PE IN (SELECT ALF_PE FROM SESSION.Cohort_Q24_Events WHERE EVENT_CAT = 'PEAK_FLOW' AND (EVENT_CD =  '66YY.')) THEN 1 ELSE 0 END AS PEAK_FLOW_DIARY
, CASE WHEN  saa.ALF_PE IN (SELECT ALF_PE FROM SESSION.Cohort_Q24_Events WHERE EVENT_CAT = 'PEAK_FLOW' AND (EVENT_CD =  '66YY.') AND EVENT_DT > '2020-11-01') THEN 1 ELSE 0 END AS PEAK_FLOW_DIARY_2_YEARS
, CASE WHEN  saa.ALF_PE IN (SELECT ALF_PE FROM SESSION.Cohort_Q24_Events WHERE EVENT_CAT = 'PEAK_FLOW' AND (EVENT_CD =  '339A.' or EVENT_CD = '339B.')) THEN 1 ELSE 0 END AS BEFORE_BRONCHODILATION
, CASE WHEN  saa.ALF_PE IN (SELECT ALF_PE FROM SESSION.Cohort_Q24_Events WHERE EVENT_CAT = 'PEAK_FLOW' AND (EVENT_CD =  '339A.' or EVENT_CD = '339B.') AND EVENT_DT > '2020-11-01') THEN 1 ELSE 0 END AS BEFORE_BRONCHODILATION_2_YEARS
FROM sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY saa
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC1_Q24
ORDER BY ALF_PE

-- DROP TABLE FOR ALTERATIONS 
DROP TABLE sailw1317v.SS_GC1_Q24

--CREATE PERMINENT TABLE
CREATE TABLE sailw1317v.SS_GC1_Q24
(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, PEAK_FLOW_FLAG INT
, PEAK_FLOW_FLAG_2_YEARS INT
, PEAK_FLOW_DIARY INT
, PEAK_FLOW_DIARY_2_YEARS INT
, BEFORE_BRONCHODILATION INT
, BEFORE_BRONCHODILATION_2_YEARS INT)

INSERT INTO  sailw1317v.SS_GC1_Q24
SELECT TABLE_ID 
,ALF_PE  
,WOB
,AGE_AT_END_OF_FOLLOW_UP  
,FIRST_EVENT
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, PEAK_FLOW_FLAG
, PEAK_FLOW_FLAG_2_YEARS
, PEAK_FLOW_DIARY
, PEAK_FLOW_DIARY_2_YEARS
, BEFORE_BRONCHODILATION
, BEFORE_BRONCHODILATION_2_YEARS
FROM SESSION.GC1_Q24

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC1_Q24

--2.5 FeNO
DECLARE GLOBAL TEMPORARY TABLE Cohort_Q25_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.EVENT_CAT, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SESSION.Q23 AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD 
AND EVENT_CAT = 'FENO'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC1_Q25 AS (
SELECT saa.* 
, CASE WHEN saa.ALF_PE IN (SELECT ALF_PE FROM SESSION.Cohort_Q23_Events WHERE EVENT_CAT = 'FENO' ) THEN 1 ELSE 0 END AS FENO_FLAG
FROM sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY saa
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC1_Q25
ORDER BY ALF_PE

-- DROP TABLE FOR ALTERATIONS 
DROP TABLE sailw1317v.SS_GC1_Q25

--CREATE PERMINENT TABLE
CREATE TABLE sailw1317v.SS_GC1_Q25
(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, FENO_FLAG INT)

INSERT INTO  sailw1317v.SS_GC1_Q25
SELECT TABLE_ID 
,ALF_PE  
,WOB
,AGE_AT_END_OF_FOLLOW_UP  
,FIRST_EVENT
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, FENO_FLAG
FROM SESSION.GC1_Q25

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC1_Q25

--2.6 Spirometry & spirometry + reversibility 
--Spirometry:
--No post-bronchodilator ratio code
--No pre-bronchodilator ratio code
--Post-bronchodilator ratio between 0.2 and 0.7
--Pre-bronchodilator ratio between 0.2 and 0.7
--Any ratio code between 0.2 and 0.7
--Spirometry + reversibility:
--No spirometry
--Any FEV1/FVC ratio code with a reversibility code
--Any spirometry code with a reversibility code

SELECT * FROM SESSION.SPIROMETRY_CORRECTED_2

SELECT * FROM  SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101

DECLARE GLOBAL TEMPORARY TABLE Cohort_Q26_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, wgec.EVENT_DT, sc.EVENT_VAL, CATEGORY
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ26_SPIROMETRY  AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN SESSION.SPIROMETRY_CORRECTED_2 sc ON wgec.EVENT_CD = sc.EVENT_CD AND wgec.ALF_PE = sc.ALF_PE AND wgec.EVENT_DT= sc.EVENT_DT
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE Rev AS ( 
SELECT ALF_PE FROM SESSION.Cohort_Q26_Events WHERE CATEGORY = 'Reversibility' 
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE Rev_FVC AS ( 
SELECT c26.ALF_PE FROM SESSION.Cohort_Q26_Events c26 INNER JOIN SESSION.REV r ON c26.ALF_PE = r.ALF_PE WHERE CATEGORY = 'FEV1/FVC ratio'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC1_Q26 AS (
SELECT saa.* 
, CASE WHEN saa.ALF_PE IN (SELECT ALF_PE FROM SESSION.Cohort_Q26_Events WHERE EVENT_CD NOT IN ('339m.', '339h0', '339b.') ) THEN 1 ELSE 0 END AS No_post_bronchodilator_ratio_code
, CASE WHEN saa.ALF_PE IN (SELECT ALF_PE FROM SESSION.Cohort_Q26_Events WHERE EVENT_CD NOT IN ('339l.', '339a.') ) THEN 1 ELSE 0 END AS No_pre_bronchodilator_ratio_code
, CASE WHEN saa.ALF_PE IN (SELECT ALF_PE FROM SESSION.Cohort_Q26_Events WHERE EVENT_CD IN ('339m.', '339h0', '339b.') AND EVENT_VAL BETWEEN '0.2' AND '0.7') THEN 1 ELSE 0 END AS Post_bronchodilator_ratio_code
, CASE WHEN saa.ALF_PE IN (SELECT ALF_PE FROM SESSION.Cohort_Q26_Events WHERE EVENT_CD IN ('339l.', '339a.') AND EVENT_VAL BETWEEN '0.2' AND '0.7' ) THEN 1 ELSE 0 END AS pre_bronchodilator_ratio_code
, CASE WHEN saa.ALF_PE IN (SELECT ALF_PE FROM SESSION.Cohort_Q26_Events ) THEN 0 ELSE 1 END AS No_Spirometry_Flag
, CASE WHEN saa.ALF_PE IN (SELECT ALF_PE FROM SESSION.Rev_FVC) THEN 1 ELSE 0 END AS FVC_REVERSIBILITY_FLAG
, CASE WHEN saa.ALF_PE IN (SELECT ALF_PE FROM SESSION.Cohort_Q26_Events WHERE CATEGORY = 'Reversibility') THEN 1 ELSE 0 END AS REVERSIBILITY_FLAG
FROM sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY saa
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC1_Q26
ORDER BY ALF_PE

SELECT * FROM SESSION.Cohort_Q26_Events
WHERE EVENT_CD = 'O339T.'


-- DROP TABLE FOR ALTERATIONS 
DROP TABLE sailw1317v.SS_GC1_Q26

--CREATE PERMINENT TABLE
CREATE TABLE sailw1317v.SS_GC1_Q26
(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, No_post_bronchodilator_ratio_code INT
, No_pre_bronchodilator_ratio_code INT
, Post_bronchodilator_ratio_code INT
, pre_bronchodilator_ratio_code INT
, No_Spirometry_Flag INT
, FVC_REVERSIBILITY_FLAG INT
, REVERSIBILITY_FLAG INT)

INSERT INTO  sailw1317v.SS_GC1_Q26
SELECT TABLE_ID 
,ALF_PE  
,WOB
,AGE_AT_END_OF_FOLLOW_UP  
,FIRST_EVENT
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, No_post_bronchodilator_ratio_code 
, No_pre_bronchodilator_ratio_code 
, Post_bronchodilator_ratio_code 
, pre_bronchodilator_ratio_code 
, No_Spirometry_Flag 
, FVC_REVERSIBILITY_FLAG 
, REVERSIBILITY_FLAG
FROM SESSION.GC1_Q26

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC1_Q26

--3.4 Oral steroids & specialist referral
--Number of people prescribed 3 or more courses of OCS in the past year
--Number of people prescribed 3 or more OCS and referred to specialist care in the past year

DECLARE GLOBAL TEMPORARY TABLE Cohort_Q34_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ34_ASTHMA_OCS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND wgec.EVENT_DT BETWEEN '2020-11-01' AND '2021-11-01'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE Cohort_Q34_Events_PT2 AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ34_ASTHMA_SPECIALIST AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND wgec.EVENT_DT BETWEEN '2020-11-01' AND '2021-11-01'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC1_Q34 AS (
SELECT saa.* 
, CASE WHEN saa.ALF_PE IN (SELECT DISTINCT ALF_PE FROM SESSION.Cohort_Q34_Events GROUP BY ALF_PE HAVING COUNT(*) > 2) THEN 1 ELSE 0 END AS OCS_PAST_YEAR
, CASE WHEN saa.ALF_PE IN (SELECT DISTINCT ALF_PE FROM SESSION.Cohort_Q34_Events_PT2 GROUP BY ALF_PE HAVING COUNT(*) > 2) THEN 1 ELSE 0 END AS OCS_AND_CARE_PAST_YEAR
FROM sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY saa
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC1_Q34
ORDER BY ALF_PE

-- DROP TABLE FOR ALTERATIONS 
DROP TABLE sailw1317v.SS_GC1_Q34

--CREATE PERMINENT TABLE
CREATE TABLE sailw1317v.SS_GC1_Q34
(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, OCS_PAST_YEAR INT
, OCS_AND_CARE_PAST_YEAR INT)

INSERT INTO  sailw1317v.SS_GC1_Q34
SELECT TABLE_ID 
,ALF_PE  
,WOB
,AGE_AT_END_OF_FOLLOW_UP  
,FIRST_EVENT
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, OCS_PAST_YEAR 
, OCS_AND_CARE_PAST_YEAR
FROM SESSION.GC1_Q34

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC1_Q34


--3.5 Smoking status
--Number of people with each smoking status or ‘not asked about smoking’ in the past year -- CATEGORY AND PATIENT ID LIST NOT COUNTS -- WIP 

SELECT * FROM sailw1317v.AQ35_SMOKING_STATUS ass 

DECLARE GLOBAL TEMPORARY TABLE Cohort_Q35_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT, AAC.CATEGORY 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ35_SMOKING_STATUS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC1_Q35 AS(
SELECT q.* FROM SESSION.Cohort_Q35_Events q
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON q.ALF_PE = SSA.ALF_PE
WHERE q.alf_PE = SSA.ALF_PE
GROUP BY q.ALF_PE, q.EVENT_CD, q.TERM, q.EVENT_DT, q.CATEGORY 
ORDER BY q.ALF_PE, q.EVENT_DT
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- DROP TABLE FOR ALTERATIONS 
DROP TABLE sailw1317v.SS_GC1_Q35

--CREATE PERMINENT TABLE
CREATE TABLE sailw1317v.SS_GC1_Q35
(
 ALF_PE VARCHAR(100), EVENT_CD VARCHAR(100), TERM VARCHAR(100), EVENT_DT DATE, CATEGORY VARCHAR(100)
)

INSERT INTO sailw1317v.SS_GC1_Q35
SELECT 
ALF_PE, EVENT_CD, TERM, EVENT_DT, CATEGORY 
FROM SESSION.GC1_Q35 
ORDER BY ALF_PE, EVENT_DT

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC1_Q35


--3.6 Secondhand smoke exposure
--Not exposed to secondhand smoke in the past year
--Exposed to secondhand smoke in the past year
--Not asked about exposure to secondhand smoke in the past year

DECLARE GLOBAL TEMPORARY TABLE Cohort_Q36_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, AAC.CATEGORY, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ36_2NDHAND_SMOKE AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC1_Q36 AS (
SELECT saa.* 
, CASE WHEN saa.ALF_PE IN (SELECT DISTINCT ALF_PE FROM SESSION.Cohort_Q36_Events WHERE CATEGORY = 'Secondhand smoke') THEN 1 ELSE 0 END AS SECOND_HAND_SMOKE_FLAG
, CASE WHEN saa.ALF_PE IN (SELECT DISTINCT ALF_PE FROM SESSION.Cohort_Q36_Events WHERE CATEGORY = 'No Secondhand smoke') THEN 1 ELSE 0 END AS NO_SECOND_HAND_SMOKE_FLAG
FROM sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY saa
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC1_Q36
ORDER BY ALF_PE

-- DROP TABLE FOR ALTERATIONS 
DROP TABLE sailw1317v.SS_GC1_Q36

--CREATE PERMINENT TABLE
CREATE TABLE sailw1317v.SS_GC1_Q36
(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, SECOND_HAND_SMOKE_FLAG INT
, NO_SECOND_HAND_SMOKE_FLAG INT)

INSERT INTO  sailw1317v.SS_GC1_Q36
SELECT TABLE_ID 
,ALF_PE  
,WOB
,AGE_AT_END_OF_FOLLOW_UP  
,FIRST_EVENT
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, SECOND_HAND_SMOKE_FLAG 
, NO_SECOND_HAND_SMOKE_FLAG 
FROM SESSION.GC1_Q36

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC1_Q36


--3.7 Asthma attacks
--- Perscription for oral steroids - any day  they didnt have annual review 
SELECT * FROM sailw1317v.AQ37_ASTHMA_ATTACKS Q37

SELECT * FROM sailw1317v.AQ37_COPD_EXACERBATIONS ace 

DECLARE GLOBAL TEMPORARY TABLE Cohort_Q37_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, AAC.CATEGORY, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ37_ASTHMA_ATTACKS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD
) WITH DATA WITH replace ON commit PRESERVE ROWS ;


DECLARE GLOBAL TEMPORARY TABLE GC1_Q37 AS ( 
SELECT * FROM SESSION.Cohort_Q37_Events
GROUP BY ALF_PE, EVENT_CD, TERM, CATEGORY, EVENT_DT
ORDER BY ALF_PE, EVENT_DT
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- DROP TABLE FOR ALTERATIONS 
DROP TABLE sailw1317v.SS_GC1_Q37

--CREATE PERMINENT TABLE
CREATE TABLE sailw1317v.SS_GC1_Q37
(
ALF_PE VARCHAR(100), 
EVENT_CD VARCHAR(100), 
TERM VARCHAR(100), 
CATEGORY VARCHAR(100),
EVENT_DT DATE)

INSERT INTO  sailw1317v.SS_GC1_Q37
SELECT 
ALF_PE  
,EVENT_CD  
,TERM 
,CATEGORY 
,EVENT_DT 
FROM SESSION.GC1_Q37

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC1_Q37

--4.2 Personalised asthma action plan
--PAAP in the past year
SELECT * FROM sailw1317v.AQ42_PAAP ap 

DECLARE GLOBAL TEMPORARY TABLE Cohort_Q42_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ42_PAAP AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND wgec.EVENT_DT BETWEEN '2020-11-01' AND '2021-11-01'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC1_Q42 AS (
SELECT saa.* 
, CASE WHEN saa.ALF_PE IN (SELECT DISTINCT ALF_PE FROM SESSION.Cohort_Q42_Events) THEN 1 ELSE 0 END AS PAAP_LAST_YEAR
FROM sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY saa
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC1_Q42
ORDER BY ALF_PE

-- DROP TABLE FOR ALTERATIONS 
DROP TABLE sailw1317v.SS_GC1_Q42

--CREATE PERMINENT TABLE
CREATE TABLE sailw1317v.SS_GC1_Q42
(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, PAAP_LAST_YEAR INT)

INSERT INTO  sailw1317v.SS_GC1_Q42
SELECT TABLE_ID 
,ALF_PE  
,WOB
,AGE_AT_END_OF_FOLLOW_UP  
,FIRST_EVENT
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, PAAP_LAST_YEAR
FROM SESSION.GC1_Q42

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC1_Q42

--4.3 RCP 3 questions
--RCP 3 questions asked in the last year

SELECT * FROM sailw1317v.AQ43_RCP_3Q arq 

DECLARE GLOBAL TEMPORARY TABLE Cohort_Q43_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ43_RCP_3Q AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND wgec.EVENT_DT BETWEEN '2020-11-01' AND '2021-11-01'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC1_Q43 AS (
SELECT saa.* 
, CASE WHEN saa.ALF_PE IN (SELECT DISTINCT ALF_PE FROM SESSION.Cohort_Q43_Events) THEN 1 ELSE 0 END AS RCP_LAST_YEAR
FROM sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY saa
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC1_Q43
ORDER BY ALF_PE


-- DROP TABLE FOR ALTERATIONS 
DROP TABLE sailw1317v.SS_GC1_Q43

--CREATE PERMINENT TABLE
CREATE TABLE sailw1317v.SS_GC1_Q43
(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, RCP_LAST_YEAR INT)

INSERT INTO  sailw1317v.SS_GC1_Q43
SELECT TABLE_ID 
,ALF_PE  
,WOB
,AGE_AT_END_OF_FOLLOW_UP  
,FIRST_EVENT
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, RCP_LAST_YEAR
FROM SESSION.GC1_Q43

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC1_Q43

--4.4 SABA inhalers
--Prescribed 3 or more SABAs in the last 12 months

SELECT * FROM sailw1317v.AQ44_SABA as2 

DECLARE GLOBAL TEMPORARY TABLE Cohort_Q44_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ44_SABA AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND wgec.EVENT_DT BETWEEN '2020-11-01' AND '2021-11-01'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC1_Q44 AS (
SELECT saa.* 
, CASE WHEN saa.ALF_PE IN (SELECT DISTINCT ALF_PE FROM SESSION.Cohort_Q44_Events GROUP BY ALF_PE HAVING COUNT(*) > 2) THEN 1 ELSE 0 END AS SABA_LAST_YEAR
FROM sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY saa
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC1_Q44
ORDER BY ALF_PE

-- DROP TABLE FOR ALTERATIONS 
DROP TABLE sailw1317v.SS_GC1_Q44

--CREATE PERMINENT TABLE
CREATE TABLE sailw1317v.SS_GC1_Q44
(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, SABA_LAST_YEAR INT)

INSERT INTO  sailw1317v.SS_GC1_Q44
SELECT TABLE_ID 
,ALF_PE  
,WOB
,AGE_AT_END_OF_FOLLOW_UP  
,FIRST_EVENT
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, SABA_LAST_YEAR
FROM SESSION.GC1_Q44

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC1_Q44

--4.5 ICS devices
--Prescribed fewer than 6 ICS devices in the last 12 months

SELECT * FROM sailw1317v.AQ45_ICS ai 

DECLARE GLOBAL TEMPORARY TABLE Cohort_Q45_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN  sailw1317v.AQ45_ICS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND wgec.EVENT_DT BETWEEN '2020-11-01' AND '2021-11-01'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC1_Q45 AS (
SELECT saa.* 
, CASE WHEN saa.ALF_PE IN (SELECT DISTINCT ALF_PE FROM SESSION.Cohort_Q45_Events GROUP BY ALF_PE HAVING COUNT(*) < 6) THEN 1 ELSE 0 END AS ICS_LAST_YEAR
FROM sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY saa
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC1_Q45
ORDER BY ALF_PE

-- DROP TABLE FOR ALTERATIONS 
DROP TABLE sailw1317v.SS_GC1_Q45

--CREATE PERMINENT TABLE
CREATE TABLE sailw1317v.SS_GC1_Q45
(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, ICS_LAST_YEAR INT)

INSERT INTO  sailw1317v.SS_GC1_Q45
SELECT TABLE_ID 
,ALF_PE  
,WOB
,AGE_AT_END_OF_FOLLOW_UP  
,FIRST_EVENT
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, ICS_LAST_YEAR
FROM SESSION.GC1_Q45

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC1_Q45

--4.6 Inhaler technique check
--Number of people prescribed an inhaler who have had their technique checked in the past year


SELECT * FROM sailw1317v.AQ46_INHALER_TECHNIQUE ait 

DECLARE GLOBAL TEMPORARY TABLE Cohort_Q46_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN  sailw1317v.AQ46_INHALER_TECHNIQUE AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND wgec.EVENT_DT BETWEEN '2020-11-01' AND '2021-11-01'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC1_Q46 AS (
SELECT saa.* 
, CASE WHEN saa.ALF_PE IN (SELECT DISTINCT ALF_PE FROM SESSION.Cohort_Q46_Events WHERE EVENT_CD NOT IN ('66Yv.', '663o.')) THEN 1 ELSE 0 END AS INHALER_CHECK_LAST_YEAR
FROM sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY saa
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC1_Q46
ORDER BY ALF_PE

-- DROP TABLE FOR ALTERATIONS 
DROP TABLE sailw1317v.SS_GC1_Q46

--CREATE PERMINENT TABLE
CREATE TABLE sailw1317v.SS_GC1_Q46
(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, INHALER_CHECK_LAST_YEAR INT)

INSERT INTO  sailw1317v.SS_GC1_Q46
SELECT TABLE_ID 
,ALF_PE  
,WOB
,AGE_AT_END_OF_FOLLOW_UP  
,FIRST_EVENT
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, INHALER_CHECK_LAST_YEAR
FROM SESSION.GC1_Q46

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC1_Q46

--4.7 Influenza immunisation
--Number of people receiving the flu vaccine in the preceding 1st August to 31st March

SELECT * FROM sailw1317v.AQ47_FLU_VAX afv 

DECLARE GLOBAL TEMPORARY TABLE Cohort_Q47_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ47_FLU_VAX AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND wgec.EVENT_DT BETWEEN '2020-08-01' AND '2021-03-31'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC1_Q47 AS (
SELECT saa.* 
, CASE WHEN saa.ALF_PE IN (SELECT DISTINCT ALF_PE FROM SESSION.Cohort_Q47_Events) THEN 1 ELSE 0 END AS FLU_VAX_FLAG
FROM sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY saa
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.GC1_Q47 WHERE FLU_VAX_FLAG = '1' --54,562

SELECT * FROM SESSION.GC1_Q47
ORDER BY ALF_PE

-- DROP TABLE FOR ALTERATIONS 
DROP TABLE sailw1317v.SS_GC1_Q47

--CREATE PERMINENT TABLE
CREATE TABLE sailw1317v.SS_GC1_Q47
(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, FLU_VAX_FLAG INT)

INSERT INTO  sailw1317v.SS_GC1_Q47
SELECT TABLE_ID 
,ALF_PE  
,WOB
,AGE_AT_END_OF_FOLLOW_UP  
,FIRST_EVENT
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, FLU_VAX_FLAG
FROM SESSION.GC1_Q47

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC1_Q47

--4.8 Smoking cessation  
--Number of people recorded as current smokers at any point in the last 2 years who received a referral for a behavioural change intervention AND a stop smoking drug prescription

DECLARE GLOBAL TEMPORARY TABLE Cohort_Q48_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, AAC.CATEGORY, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ48_SMOKING_CESSATION AAC ON wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND WGEC.EVENT_DT BETWEEN '2019-11-01' AND '2021-11-01'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE Cohort_Q48_EventsPT2 AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, AAC.CATEGORY, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ35_SMOKING_STATUS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND WGEC.EVENT_DT BETWEEN '2019-11-01' AND '2021-11-01' AND CATEGORY = 'Current smoker'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC1_Q48 AS (
SELECT saa.* 
, CASE WHEN saa.ALF_PE IN (SELECT DISTINCT ALF_PE FROM SESSION.Cohort_Q48_EventsPT2 WHERE ALF_PE IN(SELECT ALF_PE FROM SESSION.Cohort_Q48_Events GROUP BY ALF_PE HAVING COUNT(DISTINCT CATEGORY ) >= 2)) THEN 1 ELSE 0 END AS SMOKING_CESSATION_FLAG
FROM sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY saa
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC1_Q48 WHERE SMOKING_CESSATION_FLAG = 1

SELECT * FROM SESSION.GC1_Q48
ORDER BY ALF_PE

-- DROP TABLE FOR ALTERATIONS 
DROP TABLE sailw1317v.SS_GC1_Q48

--CREATE PERMINENT TABLE
CREATE TABLE sailw1317v.SS_GC1_Q48
(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, SMOKING_CESSATION_FLAG INT)

INSERT INTO  sailw1317v.SS_GC1_Q48
SELECT TABLE_ID 
,ALF_PE  
,WOB
,AGE_AT_END_OF_FOLLOW_UP  
,FIRST_EVENT
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, SMOKING_CESSATION_FLAG
FROM SESSION.GC1_Q48

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC1_Q48


--4.9 Inhaled therapy
--Prescribed an inhaled drug therapy in the last 6 months
--Number of people receiving each type of prescription (categorised in codelist)

SELECT * FROM sailw1317v.AQ49_ASTHMA_INHALERS aai 

-- AQUIRE FIRST PERSCRIPTION DATE 
DECLARE GLOBAL TEMPORARY TABLE FIRST_INHALER_PERSCRIPTION AS( 
SELECT wgec.ALF_PE, MIN(wgec.EVENT_DT) AS FIRST_INHALER_PERSCRIPTION_DATE
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ49_ASTHMA_INHALERS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY saa ON wgec.ALF_PE = SAA.ALF_PE
WHERE wgec.EVENT_CD = AAC.EVENT_CD
GROUP BY wgec.ALF_PE
ORDER BY wgec.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE FIRST_INHALER_PERSCRIPTION_EVENT AS( 
SELECT DISTINCT wgec.ALF_PE, wgec.EVENT_CD AS FIRST_INHALER_PERSCRIPTION, FIRST_INHALER_PERSCRIPTION_DATE , AAC.CATEGORY
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ49_ASTHMA_INHALERS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY ssa ON wgec.ALF_PE = SSA.ALF_PE
INNER JOIN SESSION.FIRST_INHALER_PERSCRIPTION fip ON fip.ALF_PE = wgec.ALF_PE AND fip.FIRST_INHALER_PERSCRIPTION_DATE = wgec.EVENT_DT
ORDER BY wgec.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

---
DECLARE GLOBAL TEMPORARY TABLE Cohort1_Q49_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT, aac.CATEGORY
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ49_ASTHMA_INHALERS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY ssa ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND wgec.EVENT_DT BETWEEN '2021-11-01' AND '2021-05-01'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE Cohort1_Q49_Events_PT2 AS (SELECT COUNT(DISTINCT wgec.ALF_PE) AS PATIENT_COUNT, AAC.CATEGORY
FROM sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY wgec 
INNER JOIN sailw1317v.AQ49_ASTHMA_INHALERS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
WHERE wgec.EVENT_CD = aac.EVENT_CD
GROUP BY AAC.CATEGORY
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC1_Q49 AS (
SELECT saa.* 
,FIRST_INHALER_PERSCRIPTION
,FIRST_INHALER_PERSCRIPTION_DATE
, CATEGORY
, CASE WHEN saa.ALF_PE IN (SELECT DISTINCT ALF_PE FROM SESSION.Cohort1_Q49_Events) THEN 1 ELSE 0 END AS INHALER_PERSC_FLAG
FROM sailw1317v.SS_ASTHMA_ADULTS_COMORBIDITY saa
LEFT JOIN SESSION.FIRST_INHALER_PERSCRIPTION_EVENT fip ON fip.ALF_PE = saa.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC1_49
ORDER BY ALF_PE

-- Counts per drug type 
SELECT CATEGORY, COUNT(DISTINCT ALF_PE) AS NUMBER_OF_PATIENTS FROM SESSION.Cohort1_Q49_Events_PT2
GROUP BY CATEGORY

-- DROP TABLE TO ADD CHANGES
DROP TABLE sailw1317v.SS_GC1_Q49

-- Create perminent table 
CREATE TABLE sailw1317v.SS_GC1_Q49(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,CATEGORY       VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, INHALER_PERSC_FLAG INT
,FIRST_INHALER_PERSCRIPTION VARCHAR(100)
,FIRST_INHALER_PERSCRIPTION_DATE DATE)

INSERT INTO  sailw1317v.SS_GC1_Q49
SELECT TABLE_ID        
,ALF_PE         
,WOB            
,AGE_AT_END_OF_FOLLOW_UP 
,FIRST_EVENT
,GNDR_CD        
,EVENT_CD  
,CATEGORY
,EVENT_DT      
,READ_DESC     
,PRAC_CD_PE       
,LOCAL_NUM_PE       
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, INHALER_PERSC_FLAG
,FIRST_INHALER_PERSCRIPTION
,FIRST_INHALER_PERSCRIPTION_DATE
FROM SESSION.GC1_Q49

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC1_Q49 sgq 

---- GRAND COHORT TWO - CHILDREN (Ages 12-18) ---------------------------------------------------------------------------------------------------------------

SELECT * FROM sailw1317v.SS_ASTHMA_CHILD_COMORBIDITY

--4.4: further breakdown for 6-11 year olds and 12-18 year olds
SELECT * FROM sailw1317v.AQ44_SABA as2 

DECLARE GLOBAL TEMPORARY TABLE Cohort_2Q44_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ44_SABA AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_CHILD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND wgec.EVENT_DT BETWEEN '2020-11-01' AND '2021-11-01'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC2_Q44 AS (
SELECT saa.* 
, CASE WHEN saa.ALF_PE IN (SELECT DISTINCT ALF_PE FROM SESSION.Cohort_2Q44_Events WHERE AGE_AT_END_OF_FOLLOW_UP BETWEEN '6' AND '11' GROUP BY ALF_PE HAVING COUNT(*) > 3 ) THEN 1 ELSE 0 END AS RCP_LAST_YEAR_6_TO_11
, CASE WHEN saa.ALF_PE IN (SELECT DISTINCT ALF_PE FROM SESSION.Cohort_2Q44_Events WHERE AGE_AT_END_OF_FOLLOW_UP BETWEEN '12' AND '18' GROUP BY ALF_PE HAVING COUNT(*) > 3 ) THEN 1 ELSE 0 END AS RCP_LAST_YEAR_12_TO_18
FROM sailw1317v.SS_ASTHMA_CHILD_COMORBIDITY saa
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC2_Q44
ORDER BY ALF_PE

-- DROP TABLE FOR ALTERATIONS 
DROP TABLE sailw1317v.SS_GC2_Q44

--CREATE PERMINENT TABLE
CREATE TABLE sailw1317v.SS_GC2_Q44(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
 ,RCP_LAST_YEAR_6_TO_11 INT
 ,RCP_LAST_YEAR_12_TO_18 INT)

INSERT INTO sailw1317v.SS_GC2_Q44
SELECT TABLE_ID 
,ALF_PE  
,WOB
,AGE_AT_END_OF_FOLLOW_UP  
,FIRST_EVENT 
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
,RCP_LAST_YEAR_6_TO_11
,RCP_LAST_YEAR_12_TO_18
FROM SESSION.GC2_Q44

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC2_Q44

--4.5: further breakdown for 6-11 year olds and 12-18 year olds
SELECT * FROM sailw1317v.AQ45_ICS ai 

DECLARE GLOBAL TEMPORARY TABLE Cohort2_Q45_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ45_ICS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_CHILD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND wgec.EVENT_DT BETWEEN '2020-11-01' AND '2021-11-01'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.Cohort2_Q45_Events 

SELECT * FROM sailw1317v.SS_ASTHMA_CHILD_COMORBIDITY

DECLARE GLOBAL TEMPORARY TABLE GC2_Q45 AS (
SELECT ssa.* 
, CASE WHEN ssa.ALF_PE IN(SELECT DISTINCT ce.ALF_PE FROM SESSION.Cohort2_Q45_Events ce WHERE (AGE_AT_END_OF_FOLLOW_UP BETWEEN 6 AND 11) GROUP BY ALF_PE HAVING COUNT(ALF_PE) > 3 ) THEN 1 ELSE 0 END AS ICS_LAST_YEAR_6_TO_11
, CASE WHEN ssa.ALF_PE IN(SELECT DISTINCT ce.ALF_PE FROM SESSION.Cohort2_Q45_Events ce WHERE (AGE_AT_END_OF_FOLLOW_UP BETWEEN 12 AND 18) GROUP BY ALF_PE HAVING COUNT(ALF_PE) > 3 ) THEN 1 ELSE 0 END AS ICS_LAST_YEAR_12_TO_18
, CASE WHEN ssa.ALF_PE IN(SELECT DISTINCT ce.ALF_PE FROM SESSION.Cohort2_Q45_Events ce GROUP BY ALF_PE HAVING COUNT(*) < 6) THEN 1 ELSE 0 END AS ICS_LAST_YEAR
FROM sailw1317v.SS_ASTHMA_CHILD_COMORBIDITY SSA
) WITH NO DATA WITH replace ON commit PRESERVE ROWS ;

INSERT INTO SESSION.GC2_Q45
SELECT ssa.* 
, CASE WHEN ssa.ALF_PE IN(SELECT DISTINCT ce.ALF_PE FROM SESSION.Cohort2_Q45_Events ce WHERE (AGE_AT_END_OF_FOLLOW_UP BETWEEN 6 AND 11) GROUP BY ALF_PE HAVING COUNT(ALF_PE) > 3 ) THEN 1 ELSE 0 END AS ICS_LAST_YEAR_6_TO_11
, CASE WHEN ssa.ALF_PE IN(SELECT DISTINCT ce.ALF_PE FROM SESSION.Cohort2_Q45_Events ce WHERE (AGE_AT_END_OF_FOLLOW_UP BETWEEN 12 AND 18) GROUP BY ALF_PE HAVING COUNT(ALF_PE) > 3 ) THEN 1 ELSE 0 END AS ICS_LAST_YEAR_12_TO_18
, CASE WHEN ssa.ALF_PE IN(SELECT DISTINCT ce.ALF_PE FROM SESSION.Cohort2_Q45_Events ce GROUP BY ALF_PE HAVING COUNT(*) < 6) THEN 1 ELSE 0 END AS ICS_LAST_YEAR
FROM sailw1317v.SS_ASTHMA_CHILD_COMORBIDITY SSA

SELECT * FROM SESSION.GC2_Q45
ORDER BY ALF_PE

-- DROP TABLE FOR ALTERATIONS 
DROP TABLE sailw1317v.SS_GC2_Q45

--CREATE PERMINENT TABLE
CREATE TABLE sailw1317v.SS_GC2_Q45(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
 ,ICS_LAST_YEAR_6_TO_11 INT
 ,ICS_LAST_YEAR_12_TO_18 INT
 ,ICS_LAST_YEAR INT)

INSERT INTO sailw1317v.SS_GC2_Q45
SELECT TABLE_ID 
,ALF_PE  
,WOB
,AGE_AT_END_OF_FOLLOW_UP  
,FIRST_EVENT 
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, ICS_LAST_YEAR_6_TO_11
, ICS_LAST_YEAR_12_TO_18
, ICS_LAST_YEAR
FROM SESSION.GC2_Q45

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC2_Q45

--4.8: Number of people recorded as current smokers at any point in the last 2 years who received a referral for a behavioural change intervention OR a stop smoking drug prescription
DECLARE GLOBAL TEMPORARY TABLE Cohort2_Q48_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, AAC.CATEGORY, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ48_SMOKING_CESSATION AAC ON wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_CHILD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND WGEC.EVENT_DT BETWEEN '2019-11-01' AND '2021-11-01'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE Cohort2_Q48_EventsPT2 AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, AAC.CATEGORY, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ35_SMOKING_STATUS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_CHILD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND WGEC.EVENT_DT BETWEEN '2019-11-01' AND '2021-11-01' AND CATEGORY = 'Current smoker'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC2_Q48 AS (
SELECT saa.* 
, CASE WHEN saa.ALF_PE IN (SELECT DISTINCT ALF_PE FROM SESSION.Cohort2_Q48_EventsPT2 WHERE ALF_PE IN(SELECT ALF_PE FROM SESSION.Cohort2_Q48_Events GROUP BY ALF_PE HAVING COUNT(DISTINCT CATEGORY ) >= 2)) THEN 1 ELSE 0 END AS SMOKING_CESSATION_FLAG
FROM sailw1317v.SS_ASTHMA_CHILD_COMORBIDITY saa
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC1_Q48 WHERE SMOKING_CESSATION_FLAG = 1

SELECT * FROM SESSION.GC2_Q48
ORDER BY ALF_PE

-- DROP TABLE FOR ALTERATIONS 
DROP TABLE sailw1317v.SS_GC2_Q48

--CREATE PERMINENT TABLE
CREATE TABLE sailw1317v.SS_GC2_Q48(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
 ,SMOKING_CESSATION_FLAG INT)

INSERT INTO sailw1317v.SS_GC2_Q48
SELECT TABLE_ID 
,ALF_PE  
,WOB
,AGE_AT_END_OF_FOLLOW_UP  
,FIRST_EVENT 
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, SMOKING_CESSATION_FLAG
FROM SESSION.GC2_Q48

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC2_Q48

--4.9 Inhaled therapy
--Prescribed an inhaled drug therapy in the last 6 months
--Number of people receiving each type of prescription (categorised in codelist)

SELECT * FROM sailw1317v.AQ49_ASTHMA_INHALERS aai 

-- AQUIRE FIRST PERSCRIPTION DATE 
DECLARE GLOBAL TEMPORARY TABLE FIRST_INHALER_PERSCRIPTION AS( 
SELECT wgec.ALF_PE, MIN(wgec.EVENT_DT) AS FIRST_INHALER_PERSCRIPTION_DATE
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ49_ASTHMA_INHALERS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_CHILD_COMORBIDITY saa ON wgec.ALF_PE = SAA.ALF_PE
WHERE wgec.EVENT_CD = AAC.EVENT_CD
GROUP BY wgec.ALF_PE
ORDER BY wgec.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE FIRST_INHALER_PERSCRIPTION_EVENT AS( 
SELECT DISTINCT wgec.ALF_PE, wgec.EVENT_CD AS FIRST_INHALER_PERSCRIPTION, FIRST_INHALER_PERSCRIPTION_DATE , AAC.CATEGORY
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ49_ASTHMA_INHALERS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_CHILD_COMORBIDITY ssa ON wgec.ALF_PE = SSA.ALF_PE
INNER JOIN SESSION.FIRST_INHALER_PERSCRIPTION fip ON fip.ALF_PE = wgec.ALF_PE AND fip.FIRST_INHALER_PERSCRIPTION_DATE = wgec.EVENT_DT
ORDER BY wgec.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

---
DECLARE GLOBAL TEMPORARY TABLE Cohort2_Q49_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT, aac.CATEGORY
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317V.AQ49_ASTHMA_INHALERS_CHILDREN AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_CHILD_COMORBIDITY ssa ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND wgec.EVENT_DT BETWEEN '2021-11-01' AND '2021-05-01'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;


DECLARE GLOBAL TEMPORARY TABLE Cohort2_Q49_Events_PT2 AS (SELECT COUNT(DISTINCT wgec.ALF_PE) AS PATIENT_COUNT, AAC.CATEGORY
FROM sailw1317v.SS_ASTHMA_CHILD_COMORBIDITY wgec 
INNER JOIN sailw1317v.AQ49_ASTHMA_INHALERS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
WHERE wgec.EVENT_CD = aac.EVENT_CD
GROUP BY AAC.CATEGORY
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC2_Q49 AS (
SELECT saa.* 
,FIRST_INHALER_PERSCRIPTION
,FIRST_INHALER_PERSCRIPTION_DATE
, CATEGORY
, CASE WHEN saa.ALF_PE IN(SELECT ALF_PE FROM SESSION.Cohort2_Q49_Events) THEN 1 ELSE 0 END AS INHALER_PERSC_FLAG
FROM sailw1317v.SS_ASTHMA_CHILD_COMORBIDITY saa
LEFT JOIN SESSION.FIRST_INHALER_PERSCRIPTION_EVENT fip ON fip.ALF_PE = saa.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC2_49
ORDER BY ALF_PE

-- Counts per drug type 
SELECT CATEGORY, COUNT(DISTINCT ALF_PE) AS NUMBER_OF_PATIENTS FROM SESSION.Cohort2_Q49_Events_PT2
GROUP BY CATEGORY

-- DROP TABLE TO ADD CHANGES
DROP TABLE sailw1317v.SS_GC2_Q49

-- Create perminent table 
CREATE TABLE sailw1317v.SS_GC2_Q49(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,CATEGORY       VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, INHALER_PERSC_FLAG INT
,FIRST_INHALER_PERSCRIPTION VARCHAR(100)
,FIRST_INHALER_PERSCRIPTION_DATE DATE)

INSERT INTO  sailw1317v.SS_GC2_Q49
SELECT TABLE_ID        
,ALF_PE         
,WOB            
,AGE_AT_END_OF_FOLLOW_UP 
,FIRST_EVENT
,GNDR_CD        
,EVENT_CD  
,CATEGORY
,EVENT_DT      
,READ_DESC     
,PRAC_CD_PE       
,LOCAL_NUM_PE       
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, INHALER_PERSC_FLAG
,FIRST_INHALER_PERSCRIPTION
,FIRST_INHALER_PERSCRIPTION_DATE
FROM SESSION.GC2_Q49

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC2_Q49 sgq 

---- GRAND COHORT THREE - COPD Patients Audit Queries -------------------------------------------------------------------------------------------------------  

DECLARE GLOBAL TEMPORARY TABLE GC3 AS (
SELECT * FROM sailw1317v.SS_COPD_COMORBIDITY
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

----2.1 FEV1/FVC ratio
--Any ratio codes >=0.2 and <0.7
--Post-bronchodilator code (339m.) >=0.2 and <0.7
--No 339m. code

SELECT * FROM sailw1317v.AQ21_FEV1FVC_RATIO affr 

DECLARE GLOBAL TEMPORARY TABLE Cohort3_Q21_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT, wgec.EVENT_VAL 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ21_FEV1FVC_RATIO AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_COPD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD 
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC3_Q21 AS ( SELECT wgec.* 
, CASE WHEN wgec.ALF_PE IN(SELECT ALF_PE FROM SESSION.Cohort3_Q21_Events WHERE EVENT_VAL BETWEEN '0.2' AND '0.7') THEN 1 ELSE 0 END AS Ratio_Code_Flag
, CASE WHEN wgec.ALF_PE IN(SELECT ALF_PE FROM SESSION.Cohort3_Q21_Events WHERE EVENT_CD = '339m.' AND EVENT_VAL BETWEEN '0.2' AND '0.7') THEN 1 ELSE 0 END AS Post_bronchodilator_Ratio_Code_Flag
, CASE WHEN wgec.ALF_PE IN(SELECT ALF_PE FROM SESSION.Cohort3_Q21_Events WHERE EVENT_CD NOT In('339m.') AND EVENT_VAL BETWEEN '0.2' AND '0.7' GROUP BY ALF_PE) THEN 1 ELSE 0 END AS No_Post_bronchodilator_Ratio_Code_Flag
FROM sailw1317v.SS_COPD_COMORBIDITY wgec 
) WITH DATA WITH replace ON commit PRESERVE ROWS ;


SELECT * FROM SESSION.GC3_Q21
ORDER BY ALF_PE

-- DROP TABLE TO ADD CHANGES
DROP TABLE sailw1317v.SS_GC3_Q21

-- Create perminent table 
CREATE TABLE sailw1317v.SS_GC3_Q21(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, Ratio_Code_Flag int
, Post_bronchodilator_Ratio_Code_Flag int
, No_Post_bronchodilator_Ratio_Code_Flag int)

INSERT INTO  sailw1317v.SS_GC3_Q21
SELECT TABLE_ID        
,ALF_PE         
,WOB            
,AGE_AT_END_OF_FOLLOW_UP 
,FIRST_EVENT
,GNDR_CD        
,EVENT_CD        
,EVENT_DT      
,READ_DESC     
,PRAC_CD_PE       
,LOCAL_NUM_PE       
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, Ratio_Code_Flag 
, Post_bronchodilator_Ratio_Code_Flag 
, No_Post_bronchodilator_Ratio_Code_Flag
FROM SESSION.GC3_Q21

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC3_Q21

----2.2 Chest X-ray (CXR) or CT scan
--CXR/CT within 6 months of diagnosis (6 months pre/post diagnosis)
SELECT * FROM sailw1317v.SS_COPD_COMORBIDITY

SELECT * FROM sailw1317v.AQ22_XRAY ax 

DECLARE GLOBAL TEMPORARY TABLE Cohort3_Q22_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ22_XRAY AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_COPD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD 
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC3_Q22 AS ( SELECT wgec.* 
, CASE WHEN SCC.EVENT_DT BETWEEN FIRST_EVENT AND (FIRST_EVENT + 6 MONTHS) AND SCC.EVENT_CD IN(SELECT EVENT_CD FROM sailw1317v.AQ22_XRAY) THEN 1 ELSE 0 END AS XRAY_FLAG_POST_DIAGNOSIS
FROM sailw1317v.SS_COPD_COMORBIDITY wgec 
LEFT JOIN SESSION.Cohort3_Q22_Events SCC ON wgec.ALF_PE = scc.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC3_Q22
ORDER BY ALF_PE

-- DROP TABLE TO ADD CHANGES
DROP TABLE sailw1317v.SS_GC3_Q22

-- Create perminent table 
CREATE TABLE sailw1317v.SS_GC3_Q22(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, XRAY_FLAG_POST_DIAGNOSIS INT)

INSERT INTO  sailw1317v.SS_GC3_Q22
SELECT TABLE_ID        
,ALF_PE         
,WOB            
,AGE_AT_END_OF_FOLLOW_UP 
,FIRST_EVENT
,GNDR_CD        
,EVENT_CD        
,EVENT_DT      
,READ_DESC     
,PRAC_CD_PE       
,LOCAL_NUM_PE       
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, XRAY_FLAG_POST_DIAGNOSIS
FROM SESSION.GC3_Q22

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT DISTINCT * FROM sailw1317v.SS_GC3_Q22
ORDER BY ALF_PE 

--3.1 MRC grade
--Proportion of each score or ‘not recorded’ in the past year
SELECT * FROM sailw1317v.AQ31_MRC am 

--calculate latest MRC GRADE 
DECLARE GLOBAL TEMPORARY TABLE LATEST_EVENT AS( SELECT wgec.ALF_PE, MAX(wgec.EVENT_DT) AS LATEST_DATE
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec  
INNER JOIN sailw1317v.AQ31_MRC AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_COPD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = AAC.EVENT_CD
GROUP BY wgec.ALF_PE
ORDER BY wgec.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE LATEST_MRC AS( 
SELECT wgec.ALF_PE, MRC_GRADE, LATEST_DATE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec  
INNER JOIN sailw1317v.AQ31_MRC AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_COPD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
INNER JOIN SESSION.LATEST_EVENT le ON le.LATEST_DATE = wgec.EVENT_DT AND le.ALF_PE = wgec.ALF_PE 
WHERE le.LATEST_DATE = wgec.EVENT_DT
GROUP BY wgec.ALF_PE, MRC_GRADE, LATEST_DATE 
ORDER BY wgec.ALF_PE, MRC_GRADE, LATEST_DATE 
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE Cohort3_Q31_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, AAC.MRC_GRADE, wgec.EVENT_DT, le.MRC_GRADE AS LATEST_MRC 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec  
INNER JOIN sailw1317v.AQ31_MRC AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_COPD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
LEFT JOIN SESSION. LATEST_MRC le ON le.LATEST_DATE = wgec.EVENT_DT AND le.ALF_PE = wgec.ALF_PE 
WHERE wgec.EVENT_CD = aac.EVENT_CD AND wgec.EVENT_DT BETWEEN '2020-11-01' AND '2021-11-01'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC3_Q312 AS (
SELECT saa.ALF_PE, saa.EVENT_CD , saa.EVENT_DT, TERM, LATEST_MRC
FROM sailw1317v.SS_COPD_COMORBIDITY saa
LEFT JOIN SESSION.Cohort3_Q31_Events wgec ON  wgec.ALF_PE = saa.ALF_PE 
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC3_Q31 AS (
SELECT LATEST_MRC, COUNT(DISTINCT ALF_PE) AS NUMBER_OF_PATIENTS FROM SESSION.GC3_Q312
GROUP BY LATEST_MRC
ORDER BY LATEST_MRC
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC3_Q31

-- DROP TABLE TO ADD CHANGES
DROP TABLE sailw1317v.SS_GC3_Q31

-- Create perminent table 
CREATE TABLE sailw1317v.SS_GC3_Q31(
LATEST_MRC VARCHAR(100) 
,NUMBER_OF_PATIENTS INT)

INSERT INTO  sailw1317v.SS_GC3_Q31
SELECT LATEST_MRC 
,NUMBER_OF_PATIENTS
FROM SESSION.GC3_Q31

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC3_Q31

----3.2 FEV1 %-predicted
--Recorded in the last year
SELECT * FROM sailw1317v.AQ32_FEV1_PCPREDICTED afp 

DECLARE GLOBAL TEMPORARY TABLE Cohort3_Q32_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ32_FEV1_PCPREDICTED AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_COPD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND wgec.EVENT_DT BETWEEN '2020-11-01' AND '2021-11-01'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC3_Q32 AS (
SELECT saa.* 
, CASE WHEN saa.ALF_PE IN (SELECT DISTINCT ALF_PE FROM SESSION.Cohort3_Q32_Events) THEN 1 ELSE 0 END AS PAAP_LAST_YEAR
FROM sailw1317v.SS_COPD_COMORBIDITY saa
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC3_32
ORDER BY ALF_PE


-- DROP TABLE TO ADD CHANGES
DROP TABLE sailw1317v.SS_GC3_Q32

-- Create perminent table 
CREATE TABLE sailw1317v.SS_GC3_Q32(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, PAAP_LAST_YEAR INT)

INSERT INTO  sailw1317v.SS_GC3_Q32
SELECT TABLE_ID        
,ALF_PE         
,WOB            
,AGE_AT_END_OF_FOLLOW_UP 
,FIRST_EVENT
,GNDR_CD        
,EVENT_CD        
,EVENT_DT      
,READ_DESC     
,PRAC_CD_PE       
,LOCAL_NUM_PE       
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, PAAP_LAST_YEAR
FROM SESSION.GC3_Q32

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC3_Q32


----3.3 Oxygen saturation -- WIP
--People with a single oxygen saturation of 92% or less in the past 2 years
--People with at least 2 measurements (within 3 months of each other) of oxygen saturation 92% or less in the past 2 years
SELECT * FROM sailw1317v.AQ33_OXYGEN_SAT aos 

DECLARE GLOBAL TEMPORARY TABLE Cohort3_Q33_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT, wgec.EVENT_VAL 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ33_OXYGEN_SAT AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_COPD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD 
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC3_Q33 AS ( 
SELECT wgec.* 
, CASE WHEN wgec.ALF_PE IN(SELECT ALF_PE FROM SESSION.Cohort3_Q33_Events WHERE EVENT_VAL < '92'GROUP BY ALF_PE HAVING (COUNT(DISTINCT ALF_PE) = 1)) THEN 1 ELSE 0 END AS LESS_THAN_92_OXYGEN_SAT
FROM sailw1317v.SS_COPD_COMORBIDITY wgec 
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.Cohort3_Q33_Events

SELECT * FROM SESSION.GC3_Q33
ORDER BY ALF_PE

--, CASE WHEN wgec.ALF_PE IN(SELECT ALF_PE FROM SESSION.Cohort3_Q33_Events WHERE EVENT_VAL < '92' AND EVENT_DT = + 3 MONTHS) GROUP BY ALF_PE HAVING COUNT(ALF_PE) >= 2) THEN 1 ELSE 0 END AS LESS_THAN_92_OXYGEN_SAT_TWICE

-- DROP TABLE TO ADD CHANGES
DROP TABLE sailw1317v.SS_GC3_Q33

-- Create perminent table 
CREATE TABLE sailw1317v.SS_GC3_Q33(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, LESS_THAN_92_OXYGEN_SAT INT)

INSERT INTO  sailw1317v.SS_GC3_Q33
SELECT TABLE_ID        
,ALF_PE         
,WOB            
,AGE_AT_END_OF_FOLLOW_UP 
,FIRST_EVENT
,GNDR_CD        
,EVENT_CD        
,EVENT_DT      
,READ_DESC     
,PRAC_CD_PE       
,LOCAL_NUM_PE       
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, LESS_THAN_92_OXYGEN_SAT
FROM SESSION.GC3_Q33

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC3_Q33

----3.5 Smoking status
--Number of people with each smoking status or ‘not asked about smoking’ in the past year
 SELECT * FROM sailw1317v.AQ35_SMOKING_STATUS ass 

DECLARE GLOBAL TEMPORARY TABLE Cohort3_Q35_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT, AAC.CATEGORY 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ35_SMOKING_STATUS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_COPD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC3_Q35 AS(
SELECT * FROM SESSION.Cohort3_Q35_Events
GROUP BY ALF_PE, EVENT_CD, TERM, EVENT_DT, CATEGORY 
ORDER BY ALF_PE, EVENT_DT
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- DROP TABLE FOR ALTERATIONS 
DROP TABLE sailw1317v.SS_GC3_Q35

--CREATE PERMINENT TABLE
CREATE TABLE sailw1317v.SS_GC3_Q35
(
 ALF_PE VARCHAR(100), EVENT_CD VARCHAR(100), TERM VARCHAR(100), EVENT_DT DATE, CATEGORY VARCHAR(100)
)

INSERT INTO  sailw1317v.SS_GC3_Q35
SELECT 
ALF_PE, EVENT_CD, TERM, EVENT_DT, CATEGORY 
FROM SESSION.GC3_Q35 
ORDER BY ALF_PE, EVENT_DT

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC3_Q35


--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC3_Q35

----3.7 Exacerbations 

SELECT * FROM sailw1317v.AQ37_ASTHMA_ATTACKS Q37

DECLARE GLOBAL TEMPORARY TABLE Cohort_Q37_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, AAC.CATEGORY, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ37_COPD_EXACERBATIONS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_COPD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC3_Q37 as(
SELECT * FROM SESSION.Cohort_Q37_Events
GROUP BY ALF_PE, EVENT_CD, TERM, CATEGORY, EVENT_DT
ORDER BY ALF_PE, EVENT_DT
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC3_Q37
ORDER BY ALF_PE

-- DROP TABLE TO ADD CHANGES
DROP TABLE sailw1317v.SS_GC3_Q37

-- Create perminent table 
CREATE TABLE sailw1317v.SS_GC3_Q37(
ALF_PE VARCHAR(100)
, EVENT_CD VARCHAR(100)
, TERM VARCHAR(100)
, CATEGORY VARCHAR(100)
, EVENT_DT DATE)

INSERT INTO  sailw1317v.SS_GC3_Q37
SELECT ALF_PE 
, EVENT_CD 
, TERM 
, CATEGORY
, EVENT_DT 
FROM SESSION.GC3_Q37

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC3_Q37

----4.1 Pulmonary rehabilitation
--Referred to PR (with MRC >=3) in the past 3 years
--Referred to PR (any MRC score [exclude those without an MRC score]) in the past 3 years
SELECT * FROM sailw1317v.AQ41_PULMONARY_REHAB apr 

DECLARE GLOBAL TEMPORARY TABLE Cohort3_Q41_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT, wgec.EVENT_VAL 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ41_PULMONARY_REHAB AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_COPD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC3_Q41 AS (SELECT wgec.* 
, CASE WHEN wgec.ALF_PE IN(SELECT ALF_PE FROM SESSION.Cohort3_Q41_Events WHERE EVENT_CD = '8H7u.' GROUP BY ALF_PE, EVENT_DT HAVING COUNT(ALF_PE) >= 3) THEN 1 ELSE 0 END AS More_Than_3_PR_Code_Flag
, CASE WHEN wgec.ALF_PE IN(SELECT ALF_PE FROM SESSION.Cohort3_Q41_Events) THEN 1 ELSE 0 END AS PR_Code_Flag
FROM sailw1317v.SS_COPD_COMORBIDITY wgec 
WHERE EVENT_DT BETWEEN '2018-11-01' AND '2021-11-01' 
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC3_Q41
ORDER BY ALF_PE

-- DROP TABLE TO ADD CHANGES
DROP TABLE sailw1317v.SS_GC3_Q41

-- Create perminent table 
CREATE TABLE sailw1317v.SS_GC3_Q41(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, More_Than_3_PR_Code_Flag INT
, PR_Code_Flag INT)

INSERT INTO  sailw1317v.SS_GC3_Q41
SELECT TABLE_ID        
,ALF_PE         
,WOB            
,AGE_AT_END_OF_FOLLOW_UP 
,FIRST_EVENT
,GNDR_CD        
,EVENT_CD        
,EVENT_DT      
,READ_DESC     
,PRAC_CD_PE       
,LOCAL_NUM_PE       
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, More_Than_3_PR_Code_Flag
, PR_Code_Flag
FROM SESSION.GC3_Q41

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC3_Q41


--4.6 Inhaler technique check
--Number of people prescribed an inhaler who have had their technique checked in the past year

SELECT * FROM sailw1317v.AQ46_INHALER_TECHNIQUE ait 

DECLARE GLOBAL TEMPORARY TABLE Cohort3_Q46_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN  sailw1317v.AQ46_INHALER_TECHNIQUE AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_COPD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND wgec.EVENT_DT BETWEEN '2020-11-01' AND '2021-11-01'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC3_Q46 AS (
SELECT saa.* 
, CASE WHEN saa.ALF_PE IN (SELECT DISTINCT ALF_PE FROM SESSION.Cohort3_Q46_Events WHERE EVENT_CD NOT IN ('66Yv.', '663o.')) THEN 1 ELSE 0 END AS INHALER_CHECK_LAST_YEAR
FROM sailw1317v.SS_COPD_COMORBIDITY saa
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC3_46
ORDER BY ALF_PE

-- DROP TABLE TO ADD CHANGES
DROP TABLE sailw1317v.SS_GC3_Q46

-- Create perminent table 
CREATE TABLE sailw1317v.SS_GC3_Q46(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, INHALER_CHECK_LAST_YEAR INT)

INSERT INTO  sailw1317v.SS_GC3_Q46
SELECT TABLE_ID        
,ALF_PE         
,WOB            
,AGE_AT_END_OF_FOLLOW_UP 
,FIRST_EVENT
,GNDR_CD        
,EVENT_CD        
,EVENT_DT      
,READ_DESC     
,PRAC_CD_PE       
,LOCAL_NUM_PE       
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, INHALER_CHECK_LAST_YEAR
FROM SESSION.GC3_Q46

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC3_Q46

--4.7 Influenza immunisation
--Number of people receiving the flu vaccine in the preceding 1st August to 31st March

SELECT * FROM sailw1317v.AQ47_FLU_VAX afv 

DECLARE GLOBAL TEMPORARY TABLE Cohort3_Q47_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ47_FLU_VAX AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_COPD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND wgec.EVENT_DT BETWEEN '2020-08-01' AND '2021-03-31'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC3_Q47 AS (
SELECT saa.* 
, CASE WHEN saa.ALF_PE IN (SELECT DISTINCT ALF_PE FROM SESSION.Cohort3_Q47_Events) THEN 1 ELSE 0 END AS FLU_VAX_FLAG
FROM sailw1317v.SS_COPD_COMORBIDITY saa
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.GC1_Q47 WHERE FLU_VAX_FLAG = '1' --50,972

SELECT * FROM SESSION.GC3_47
ORDER BY ALF_PE

-- DROP TABLE TO ADD CHANGES
DROP TABLE sailw1317v.SS_GC3_Q47

-- Create perminent table 
CREATE TABLE sailw1317v.SS_GC3_Q47(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, FLU_VAX_FLAG INT)

INSERT INTO  sailw1317v.SS_GC3_Q47
SELECT TABLE_ID        
,ALF_PE         
,WOB            
,AGE_AT_END_OF_FOLLOW_UP 
,FIRST_EVENT
,GNDR_CD        
,EVENT_CD        
,EVENT_DT      
,READ_DESC     
,PRAC_CD_PE       
,LOCAL_NUM_PE       
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, FLU_VAX_FLAG
FROM SESSION.GC3_Q47

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC3_Q47

--4.8 Smoking cessation  
--Number of people recorded as current smokers at any point in the last 2 years who received a referral for a behavioural change intervention AND a stop smoking drug prescription

DECLARE GLOBAL TEMPORARY TABLE Cohort3_Q48_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, AAC.CATEGORY, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ48_SMOKING_CESSATION AAC ON wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_COPD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND WGEC.EVENT_DT BETWEEN '2019-11-01' AND '2021-11-01'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE Cohort3_Q48_EventsPT2 AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, AAC.CATEGORY, wgec.EVENT_DT 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ35_SMOKING_STATUS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_COPD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND WGEC.EVENT_DT BETWEEN '2019-11-01' AND '2021-11-01' AND CATEGORY = 'Current smoker'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT ALF_PE FROM SESSION.Cohort_Q48_Events GROUP BY ALF_PE  HAVING COUNT(DISTINCT CATEGORY) >= 2

DECLARE GLOBAL TEMPORARY TABLE GC3_Q48 AS (
SELECT saa.* 
, CASE WHEN saa.ALF_PE IN (SELECT DISTINCT ALF_PE FROM SESSION.Cohort3_Q48_EventsPT2 WHERE ALF_PE IN(SELECT ALF_PE FROM SESSION.Cohort3_Q48_Events GROUP BY ALF_PE HAVING COUNT(DISTINCT CATEGORY ) >= 2)) THEN 1 ELSE 0 END AS SMOKING_CESSATION_FLAG
FROM sailw1317v.SS_COPD_COMORBIDITY saa
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC1_Q48 WHERE SMOKING_CESSATION_FLAG = 1

SELECT * FROM SESSION.GC3_48
ORDER BY ALF_PE

-- DROP TABLE TO ADD CHANGES
DROP TABLE sailw1317v.SS_GC3_Q48

-- Create perminent table 
CREATE TABLE sailw1317v.SS_GC3_Q48(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, SMOKING_CESSATION_FLAG INT)

INSERT INTO  sailw1317v.SS_GC3_Q48
SELECT TABLE_ID        
,ALF_PE         
,WOB            
,AGE_AT_END_OF_FOLLOW_UP 
,FIRST_EVENT
,GNDR_CD        
,EVENT_CD        
,EVENT_DT      
,READ_DESC     
,PRAC_CD_PE       
,LOCAL_NUM_PE       
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, SMOKING_CESSATION_FLAG
FROM SESSION.GC3_Q48

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC3_Q48

--4.9 Inhaled therapy
--Prescribed an inhaled drug therapy in the last 6 months
--Number of people receiving each type of prescription (categorised in codelist)

SELECT * FROM sailw1317v.AQ49_ASTHMA_INHALERS aai 

-- AQUIRE FIRST PERSCRIPTION DATE 
DECLARE GLOBAL TEMPORARY TABLE FIRST_INHALER_PERSCRIPTION AS( 
SELECT wgec.ALF_PE, MIN(wgec.EVENT_DT) AS FIRST_INHALER_PERSCRIPTION_DATE
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ49_ASTHMA_INHALERS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_COPD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = AAC.EVENT_CD
GROUP BY wgec.ALF_PE
ORDER BY wgec.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE FIRST_INHALER_PERSCRIPTION_EVENT AS( 
SELECT DISTINCT wgec.ALF_PE, wgec.EVENT_CD AS FIRST_INHALER_PERSCRIPTION, FIRST_INHALER_PERSCRIPTION_DATE , AAC.CATEGORY
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ49_ASTHMA_INHALERS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_COPD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
INNER JOIN SESSION.FIRST_INHALER_PERSCRIPTION fip ON fip.ALF_PE = wgec.ALF_PE AND fip.FIRST_INHALER_PERSCRIPTION_DATE = wgec.EVENT_DT
ORDER BY wgec.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

---
DECLARE GLOBAL TEMPORARY TABLE Cohort3_Q49_Events AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, AAC.TERM, wgec.EVENT_DT, aac.CATEGORY
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN sailw1317v.AQ49_ASTHMA_INHALERS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
INNER JOIN sailw1317v.SS_COPD_COMORBIDITY SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD = aac.EVENT_CD AND wgec.EVENT_DT BETWEEN '2021-11-01' AND '2021-05-01'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE Cohort3_Q49_Events_PT2 AS (SELECT COUNT(DISTINCT wgec.ALF_PE) AS PATIENT_COUNT, AAC.CATEGORY
FROM sailw1317v.SS_COPD_COMORBIDITY wgec 
INNER JOIN sailw1317v.AQ49_ASTHMA_INHALERS AAC ON  wgec.EVENT_CD = AAC.EVENT_CD
WHERE wgec.EVENT_CD = aac.EVENT_CD
GROUP BY AAC.CATEGORY
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GC3_Q49 AS (
SELECT saa.* 
,FIRST_INHALER_PERSCRIPTION
,FIRST_INHALER_PERSCRIPTION_DATE
, CATEGORY
, CASE WHEN saa.ALF_PE IN (SELECT DISTINCT ALF_PE FROM SESSION.Cohort3_Q49_Events) THEN 1 ELSE 0 END AS INHALER_PERSC_FLAG
FROM sailw1317v.SS_COPD_COMORBIDITY saa
LEFT JOIN SESSION.FIRST_INHALER_PERSCRIPTION_EVENT fip ON fip.ALF_PE = saa.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.GC3_49
ORDER BY ALF_PE

-- Counts per drug type 
SELECT CATEGORY, COUNT(DISTINCT ALF_PE) AS NUMBER_OF_PATIENTS FROM SESSION.Cohort3_Q49_Events_PT2
GROUP BY CATEGORY

-- DROP TABLE TO ADD CHANGES
DROP TABLE sailw1317v.SS_GC3_Q49

-- Create perminent table 
CREATE TABLE sailw1317v.SS_GC3_Q49(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,FIRST_EVENT DATE
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,CATEGORY       VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100)
, INHALER_PERSC_FLAG INT
,FIRST_INHALER_PERSCRIPTION VARCHAR(100)
,FIRST_INHALER_PERSCRIPTION_DATE DATE)

INSERT INTO  sailw1317v.SS_GC3_Q49
SELECT TABLE_ID        
,ALF_PE         
,WOB            
,AGE_AT_END_OF_FOLLOW_UP 
,FIRST_EVENT
,GNDR_CD        
,EVENT_CD  
,CATEGORY
,EVENT_DT      
,READ_DESC     
,PRAC_CD_PE       
,LOCAL_NUM_PE       
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
, INHALER_PERSC_FLAG
,FIRST_INHALER_PERSCRIPTION
,FIRST_INHALER_PERSCRIPTION_DATE
FROM SESSION.GC3_Q49

--SELECT NEW TABLE FOR CSV EXTRACTION 
SELECT * FROM sailw1317v.SS_GC3_Q49 sgq 
