--------------------------------------------- Project 1317 Cohort Creation Part Two Script - 07/12/2021 ----------------------------------------------------

---- GRAND COHORT ONE - ADULTS - starts on line 15
--
--

---- GRAND COHORT TWO - CHILDREN (Ages 12-18) - starts on line 99
--
--

---- GRAND COHORT THREE - COPD Patients - starts on line 167
--
--

-------------------------- GRAND COHORT ONE - ADULTS --------------------------------------------------
-- All adults with asthma from base cohort 

DECLARE GLOBAL TEMPORARY TABLE GCH_ADULTS_Asthma AS (SELECT TABLE_ID, ALF_PE, WOB, AGE_AT_END_OF_FOLLOW_UP, GNDR_CD, EVENT_CD, EVENT_DT, READ_DESC, PRAC_CD_PE, LOCAL_NUM_PE, WIMD_2019_QUINTILE, GP_PRACTICE_CLUSTER_CODE, GP_PRACTICE_CLUSTER_NAME, LOCALHEALTHBOARDCODE, LOCALHEALTHBOARDNAME   
FROM sailw1317v.SS_BASIC_EVENTS
WHERE TABLE_ID = 'Asthma' 
AND YEAR(WOB) <= '2003'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE GCH_ADULTS_COPD AS (SELECT TABLE_ID, ALF_PE, WOB, AGE_AT_END_OF_FOLLOW_UP, GNDR_CD, EVENT_CD, EVENT_DT, READ_DESC, PRAC_CD_PE, LOCAL_NUM_PE, WIMD_2019_QUINTILE, GP_PRACTICE_CLUSTER_CODE, GP_PRACTICE_CLUSTER_NAME, LOCALHEALTHBOARDCODE, LOCALHEALTHBOARDNAME   
FROM sailw1317v.SS_BASIC_EVENTS
WHERE TABLE_ID = 'COPD' 
AND YEAR(WOB) <= '2003'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Identify those with a Asthma code followed by a COPD Code 2 years after 
DECLARE GLOBAL TEMPORARY TABLE GCH_Alfs_ASTHMA AS (SELECT DISTINCT ALF_PE, min(EVENT_DT) AS MIN_DATE
FROM sailw1317v.SS_BASIC_EVENTS
WHERE TABLE_ID = 'Asthma' 
AND YEAR(WOB) <= '2003'
GROUP BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE ALFS_COPD AS (SELECT DISTINCT gaa.ALF_PE
FROM SESSION.GCH_Alfs_ASTHMA gaa
INNER JOIN SESSION.GCH_ADULTS_COPD gac ON gaa.ALF_PE = gac.ALF_PE
WHERE (gac.EVENT_DT BETWEEN gaa.MIN_DATE AND gaa.MIN_DATE + 2 YEARS)  
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Remove those with a Later COPD Diagnosis from main cohort 
DELETE 
FROM SESSION.GCH_ADULTS_Asthma
WHERE ALF_PE IN(SELECT ALF_PE FROM SESSION.ALFS_COPD)

-- Check counts 
SELECT COUNT(*) FROM SESSION.GCH_ADULTS_ASTHMA; -- 415,488 --512,772
SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.GCH_ADULTS_ASTHMA; -- 81,219 --87,554

SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.ALFS_COPD-- 3,678 -- 4,092

-- Post Deletion 
SELECT COUNT(*) FROM SESSION.GCH_ADULTS_ASTHMA; -- 401,478
SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.GCH_ADULTS_ASTHMA; -- 81,146

-- Code to drop table before adding alterations 
DROP TABLE sailw1317v.SS_ASTHMA_ADULTS 

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ASTHMA_ADULTS(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,GNDR_CD        INT
,EVENT_CD       VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100))

INSERT INTO sailw1317v.SS_ASTHMA_ADULTS
SELECT TABLE_ID 
,ALF_PE  
,WOB   
,AGE_AT_END_OF_FOLLOW_UP  
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
FROM SESSION.GCH_ADULTS_Asthma

-------------------------- GRAND COHORT TWO - CHILDREN (Ages 12-18) -----------------------------------
DECLARE GLOBAL TEMPORARY TABLE Child_Cohort AS (SELECT TABLE_ID, ALF_PE, WOB, AGE_AT_END_OF_FOLLOW_UP, GNDR_CD, EVENT_CD, EVENT_DT, READ_DESC, PRAC_CD_PE, LOCAL_NUM_PE, WIMD_2019_QUINTILE, GP_PRACTICE_CLUSTER_CODE, GP_PRACTICE_CLUSTER_NAME, LOCALHEALTHBOARDCODE, LOCALHEALTHBOARDNAME   
FROM sailw1317v.SS_BASIC_EVENTS
WHERE YEAR(WOB) BETWEEN '2003' AND '2015'
AND TABLE_ID = 'Asthma'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- remove those with resolved codes from cohort 

DECLARE GLOBAL TEMPORARY TABLE Child_Cohort_Resolved AS (SELECT TABLE_ID, ALF_PE, WOB, AGE_AT_END_OF_FOLLOW_UP, GNDR_CD, EVENT_CD, EVENT_DT, READ_DESC, PRAC_CD_PE, LOCAL_NUM_PE, WIMD_2019_QUINTILE, GP_PRACTICE_CLUSTER_CODE, GP_PRACTICE_CLUSTER_NAME, LOCALHEALTHBOARDCODE, LOCALHEALTHBOARDNAME   
FROM sailw1317v.SS_BASIC_EVENTS
WHERE YEAR(WOB) BETWEEN '2003' AND '2015'
AND TABLE_ID = 'Asthma'
AND (EVENT_CD = '21262' OR EVENT_CD =  '212G.')
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DELETE 
FROM SESSION.Child_Cohort
WHERE ALF_PE IN(SELECT ALF_PE FROM SESSION.Child_Cohort_Resolved)

-- Check counts 
-- Pre-deletion
SELECT Count(*) FROM SESSION.Child_Cohort; --49,970 -- 56,377
SELECT Count(DISTINCT ALF_PE) FROM SESSION.Child_Cohort;--9,664 -- 10,348

SELECT Count(*) FROM SESSION.Child_Cohort_Resolved;--338 -- 363
SELECT Count(DISTINCT ALF_PE) FROM SESSION.Child_Cohort_Resolved;--278 -- 294

 --Post Deletion 
SELECT Count(*) FROM SESSION.Child_Cohort; --49,369 --56,377
SELECT Count(DISTINCT ALF_PE) FROM SESSION.Child_Cohort;--9,386 --10,348

-- Code to drop table before adding alterations 
DROP TABLE sailw1317v.SS_ASTHMA_CHILDREN 

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ASTHMA_CHILDREN(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100))

INSERT INTO sailw1317v.SS_ASTHMA_CHILDREN
SELECT TABLE_ID 
,ALF_PE  
,WOB
,AGE_AT_END_OF_FOLLOW_UP  
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE  
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME 
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME 
FROM SESSION.Child_Cohort

-------------------------- GRAND COHORT THREE - COPD Patients -----------------------------------------

DECLARE GLOBAL TEMPORARY TABLE COPD AS (SELECT TABLE_ID, ALF_PE, WOB, AGE_AT_END_OF_FOLLOW_UP, GNDR_CD, EVENT_CD, EVENT_DT, READ_DESC, PRAC_CD_PE, LOCAL_NUM_PE, WIMD_2019_QUINTILE, GP_PRACTICE_CLUSTER_CODE, GP_PRACTICE_CLUSTER_NAME, LOCALHEALTHBOARDCODE, LOCALHEALTHBOARDNAME   
FROM sailw1317v.SS_BASIC_EVENTS
WHERE YEAR(WOB) <= '1986'
AND TABLE_ID = 'COPD'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- remove those with a resolved code 
DECLARE GLOBAL TEMPORARY TABLE COPD_Resolved AS (SELECT  TABLE_ID, ALF_PE, WOB, AGE_AT_END_OF_FOLLOW_UP, GNDR_CD, EVENT_CD, EVENT_DT, READ_DESC, PRAC_CD_PE, LOCAL_NUM_PE, WIMD_2019_QUINTILE, GP_PRACTICE_CLUSTER_CODE, GP_PRACTICE_CLUSTER_NAME, LOCALHEALTHBOARDCODE, LOCALHEALTHBOARDNAME   
FROM sailw1317v.SS_BASIC_EVENTS
WHERE YEAR(WOB) <= '1986'
AND TABLE_ID = 'COPD'
AND EVENT_CD = '2126F'
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DELETE 
FROM SESSION.COPD
WHERE ALF_PE IN(SELECT ALF_PE FROM SESSION.COPD_Resolved)

-- Check Counts 
-- Pre-deletion
SELECT Count(*) FROM SESSION.COPD; --61,144 --71,118
SELECT Count(DISTINCT ALF_PE) FROM SESSION.COPD;--29,586 --32,336

SELECT Count(*) FROM SESSION.COPD_Resolved;--233 --252
SELECT Count(DISTINCT ALF_PE) FROM SESSION.COPD_Resolved;--214 --232

 --Post Deletion 
SELECT Count(*) FROM SESSION.COPD; --60,753 --71,118
SELECT Count(DISTINCT ALF_PE) FROM SESSION.COPD;--29,372 --32,336

-- Code to drop table before adding alterations 
DROP TABLE sailw1317v.SS_COPD 

-- Create perminent table 
CREATE TABLE sailw1317v.SS_COPD(
TABLE_ID        VARCHAR(100)
,ALF_PE         BIGINT
,WOB            DATE
,AGE_AT_END_OF_FOLLOW_UP  BIGINT
,GNDR_CD        INT
,EVENT_CD        VARCHAR(100)
,EVENT_DT       DATE
,READ_DESC      VARCHAR(100)
,PRAC_CD_PE        VARCHAR(100)
,LOCAL_NUM_PE       VARCHAR(100)
,WIMD_2019_QUINTILE  INT
,GP_PRACTICE_CLUSTER_CODE VARCHAR(100)
,GP_PRACTICE_CLUSTER_NAME VARCHAR(100)
,LOCALHEALTHBOARDCODE VARCHAR(100)
,LOCALHEALTHBOARDNAME VARCHAR(100))

INSERT INTO sailw1317v.SS_COPD
SELECT TABLE_ID 
,ALF_PE  
,WOB   
,AGE_AT_END_OF_FOLLOW_UP 
,GNDR_CD
,EVENT_CD   
,EVENT_DT
,READ_DESC 
,PRAC_CD_PE 
,LOCAL_NUM_PE
,WIMD_2019_QUINTILE
,GP_PRACTICE_CLUSTER_CODE 
,GP_PRACTICE_CLUSTER_NAME
,LOCALHEALTHBOARDCODE 
,LOCALHEALTHBOARDNAME
FROM SESSION.COPD