---------------- Raw Comorbidity Data Extraction ------------------ 28/03/2022 -----------------------------------------------------------------

SELECT * FROM SAILW1317V.CM_ANXIETY

SELECT * FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 
ORDER BY EVENT_DT 

-----------------------------------------------------------ADULT ASTHMA--------------------------------------------------------------------------------------------

SELECT * FROM sailw1317v.SS_ASTHMA_ADULTS

--COPD
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_COPD AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.COPD_CODES cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Drop table to add changes
DROP TABLE sailw1317v.SS_ADULT_ASTHMA_COPD

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_COPD(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100)
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_COPD
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_COPD

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_COPD

--ANXIETY
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_ANXIETY AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_ANXIETY cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD NOT IN ('8IH30', '6897.','68970')
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_ADULT_ASTHMA_ANXIETY

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_ANXIETY(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE  VARCHAR (100))

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_ANXIETY
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_ANXIETY

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_ANXIETY

-- ALLERGIC RHINITIS
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_ALLERGIC_RHINITIS AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_ALLERGIC_RHINITIS cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_ADULT_ASTHMA_ALLERGIC_RHINITIS

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_ALLERGIC_RHINITIS(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE  VARCHAR (100)
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE  VARCHAR (100))

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_ALLERGIC_RHINITIS
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_ALLERGIC_RHINITIS

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_ALLERGIC_RHINITIS

-- ATOPY
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_ATOPY AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_ATOPY cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_ADULT_ASTHMA_ATOPY

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_ATOPY(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP  VARCHAR (100)
, GNDR_CD  VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE  VARCHAR (100)
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE  VARCHAR (100))

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_ATOPY
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_ATOPY

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_ATOPY

-- BRONCHIECTASIS
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_BRONCHIECTASIS AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_BRONCHIECTASIS cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_ADULT_ASTHMA_BRONCHIECTASIS

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_BRONCHIECTASIS(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE  VARCHAR (100)
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE  VARCHAR (100))

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_BRONCHIECTASIS
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_BRONCHIECTASIS

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_BRONCHIECTASIS

-- BMI
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_BMI AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_BMI cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_ADULT_ASTHMA_BMI

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_BMI(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE  VARCHAR (100))

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_BMI
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_BMI

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_BMI

-- CHD
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_CHD AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_CHD cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_ADULT_ASTHMA_CHD

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_CHD(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100)
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_CHD
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_CHD

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_CHD

-- DIABETES 
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_DIABETES AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_DIABETES cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_DIABETES(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100)
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_DIABETES 
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_DIABETES 

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_DIABETES 

-- DEPRESSION
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_DEPRESSION AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN  SAILW1317V.CM_DEPRESSION cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD NOT IN ( '68910', '8IH31', '6891.', '6896.', 'ZV790' )
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_DEPRESSION(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100)
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_DEPRESSION
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_DEPRESSION

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_DEPRESSION

-- ECZEMA
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_ECZEMA AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_ECZEMA cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_ECZEMA(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100)
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_ECZEMA 
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_ECZEMA 

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_ECZEMA 

-- FH_ASTHMA
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_FH_ASTHMA AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_FH_ASTHMA cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD NOT IN ('122C0')
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_FH_ASTHMA(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100)
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_FH_ASTHMA
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_FH_ASTHMA

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_FH_ASTHMA

-- HAYFEVER
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_HAYFEVER AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_HAYFEVER cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_HAYFEVER(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100) )

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_HAYFEVER
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_HAYFEVER

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_HAYFEVER

-- ADULT_ASTHMA_HEART_FAILURE
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_HEART_FAILURE AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_HEART_FAILURE cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_HEART_FAILURE(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100)
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_HEART_FAILURE
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_HEART_FAILURE

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_HEART_FAILURE

--HYPERTENSION 
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_HYPERTENSION AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_HYPERTENSION cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_HYPERTENSION(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100)) 

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_HYPERTENSION
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_HYPERTENSION

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_HYPERTENSION

--LEARNING_DISABILITY
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_LEARNING_DISABILITY AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_LEARNING_DISABILITY cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_LEARNING_DISABILITY(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_LEARNING_DISABILITY
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_LEARNING_DISABILITY

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_LEARNING_DISABILITY

--LUNG_CANCER
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_LUNG_CANCER AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_LUNG_CANCER cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_LUNG_CANCER(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_LUNG_CANCER
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_LUNG_CANCER

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_LUNG_CANCER

-- NASAL_POLYPS
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_NASAL_POLYPS AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_NASAL_POLYPS cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_NASAL_POLYPS(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_NASAL_POLYPS
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_NASAL_POLYPS

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_NASAL_POLYPS

--OSTEOPOROSIS
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_OSTEOPOROSIS AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_OSTEOPOROSIS cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_ADULT_ASTHMA_OSTEOPOROSIS

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_OSTEOPOROSIS(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_OSTEOPOROSIS
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_OSTEOPOROSIS

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_OSTEOPOROSIS

-- REFLUX
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_REFLUX AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_REFLUX cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_REFLUX( 
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_REFLUX 
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_REFLUX 

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_REFLUX 

-- SMI
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_SMI AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_SMI cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_SMI( 
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100)) 

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_SMI 
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_SMI 

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_SMI 

--STROKE
DECLARE GLOBAL TEMPORARY TABLE ADULT_ASTHMA_STROKE AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_STROKE cc ON cc.EVENT_CD = wgec.EVENT_CD 
INNER JOIN sailw1317v.SS_ASTHMA_ADULTS SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_ADULT_ASTHMA_STROKE(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_ADULT_ASTHMA_STROKE
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.ADULT_ASTHMA_STROKE

SELECT * FROM sailw1317v.SS_ADULT_ASTHMA_STROKE

-----------------------------------------------------------CHILD ASTHMA--------------------------------------------------------------------------------------------
DECLARE GLOBAL TEMPORARY TABLE CHILD_ASTHMA_COPD AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.COPD_CODES cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_CHILDREN SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_CHILD_ASTHMA_COPD

-- Create perminent table 
CREATE TABLE sailw1317v.SS_CHILD_ASTHMA_COPD(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_CHILD_ASTHMA_COPD
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.CHILD_ASTHMA_COPD

SELECT * FROM sailw1317v.SS_CHILD_ASTHMA_COPD

--ALLERGIC_RHINITIS
DECLARE GLOBAL TEMPORARY TABLE CHILD_ASTHMA_ALLERGIC_RHINITIS AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_ALLERGIC_RHINITIS cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_CHILDREN SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_CHILD_ASTHMA_ALLERGIC_RHINITIS(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_CHILD_ASTHMA_ALLERGIC_RHINITIS
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.CHILD_ASTHMA_ALLERGIC_RHINITIS

SELECT * FROM sailw1317v.SS_CHILD_ASTHMA_ALLERGIC_RHINITIS

--ATOPY 
DECLARE GLOBAL TEMPORARY TABLE CHILD_ASTHMA_ATOPY AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_ATOPY cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_CHILDREN SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_CHILD_ASTHMA_ATOPY(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_CHILD_ASTHMA_ATOPY
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.CHILD_ASTHMA_ATOPY

SELECT * FROM sailw1317v.SS_CHILD_ASTHMA_ATOPY

--BMI
DECLARE GLOBAL TEMPORARY TABLE CHILD_ASTHMA_BMI AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_BMI cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_CHILDREN SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_CHILD_ASTHMA_BMI(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_CHILD_ASTHMA_BMI
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.CHILD_ASTHMA_BMI

SELECT * FROM sailw1317v.SS_CHILD_ASTHMA_BMI

--ECZEMA
DECLARE GLOBAL TEMPORARY TABLE CHILD_ASTHMA_ECZEMA AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_ECZEMA cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_CHILDREN SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_CHILD_ASTHMA_ECZEMA(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_CHILD_ASTHMA_ECZEMA
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.CHILD_ASTHMA_ECZEMA

SELECT * FROM sailw1317v.SS_CHILD_ASTHMA_ECZEMA

-- FH_ASTHMA
DECLARE GLOBAL TEMPORARY TABLE CHILD_ASTHMA_FH_ASTHMA AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_FH_ASTHMA cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_CHILDREN SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD NOT IN ('122C0')
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_CHILD_ASTHMA_FH_ASTHMA(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_CHILD_ASTHMA_FH_ASTHMA
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.CHILD_ASTHMA_FH_ASTHMA

SELECT * FROM sailw1317v.SS_CHILD_ASTHMA_FH_ASTHMA

--HAYFEVER
DECLARE GLOBAL TEMPORARY TABLE CHILD_ASTHMA_HAYFEVER AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_HAYFEVER cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_CHILDREN SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_CHILD_ASTHMA_HAYFEVER(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100)) 

INSERT INTO sailw1317v.SS_CHILD_ASTHMA_HAYFEVER
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.CHILD_ASTHMA_HAYFEVER

SELECT * FROM sailw1317v.SS_CHILD_ASTHMA_HAYFEVER


--LEARNING_DISABILITY 
DECLARE GLOBAL TEMPORARY TABLE CHILD_ASTHMA_LEARNING_DISABILITY AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_LEARNING_DISABILITY cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_CHILDREN SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_CHILD_ASTHMA_LEARNING_DISABILITY(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_CHILD_ASTHMA_LEARNING_DISABILITY
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.CHILD_ASTHMA_LEARNING_DISABILITY

SELECT * FROM sailw1317v.SS_CHILD_ASTHMA_LEARNING_DISABILITY


--NASAL_POLYPS

DECLARE GLOBAL TEMPORARY TABLE CHILD_ASTHMA_NASAL_POLYPS AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_NASAL_POLYPS cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_CHILDREN SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_CHILD_ASTHMA_NASAL_POLYPS

-- Create perminent table 
CREATE TABLE sailw1317v.SS_CHILD_ASTHMA_NASAL_POLYPS(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100)) 

INSERT INTO sailw1317v.SS_CHILD_ASTHMA_NASAL_POLYPS 
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.CHILD_ASTHMA_NASAL_POLYPS 

SELECT * FROM sailw1317v.SS_CHILD_ASTHMA_NASAL_POLYPS 

-- REFLUX
DECLARE GLOBAL TEMPORARY TABLE CHILD_ASTHMA_REFLUX AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_REFLUX cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_CHILDREN SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_CHILD_ASTHMA_REFLUX(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_CHILD_ASTHMA_REFLUX
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.CHILD_ASTHMA_REFLUX

SELECT * FROM sailw1317v.SS_CHILD_ASTHMA_REFLUX

-- MENTAL_HEALTH_PAEDS 
DECLARE GLOBAL TEMPORARY TABLE CHILD_ASTHMA_MENTAL_HEALTH_PAEDS AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_MENTAL_HEALTH_PAEDS cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_ASTHMA_CHILDREN SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Create perminent table 
CREATE TABLE sailw1317v.SS_CHILD_ASTHMA_MENTAL_HEALTH_PAEDS(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100)
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_CHILD_ASTHMA_MENTAL_HEALTH_PAEDS
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.CHILD_ASTHMA_MENTAL_HEALTH_PAEDS

SELECT * FROM sailw1317v.SS_CHILD_ASTHMA_MENTAL_HEALTH_PAEDS

-----------------------------------------------------------COPD--------------------------------------------------------------------------------------------

DECLARE GLOBAL TEMPORARY TABLE COPD_ASTHMA AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.ASTHMA_CODES cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_COPD SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_COPD_ASTHMA

-- Create perminent table 
CREATE TABLE sailw1317v.SS_COPD_ASTHMA(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_COPD_ASTHMA
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.COPD_ASTHMA

SELECT * FROM sailw1317v.SS_COPD_ASTHMA

--ANXIETY 
DECLARE GLOBAL TEMPORARY TABLE COPD_ANXIETY AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_ANXIETY cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_COPD SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD NOT IN ('8IH30', '6897.','68970')
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_COPD_ANXIETY

-- Create perminent table 
CREATE TABLE sailw1317v.SS_COPD_ANXIETY(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_COPD_ANXIETY
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.COPD_ANXIETY

SELECT * FROM sailw1317v.SS_COPD_ANXIETY

--BRONCHIECTASIS
DECLARE GLOBAL TEMPORARY TABLE COPD_BRONCHIECTASIS AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_BRONCHIECTASIS cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_COPD SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;


DROP TABLE sailw1317v.SS_COPD_BRONCHIECTASIS

-- Create perminent table 
CREATE TABLE sailw1317v.SS_COPD_BRONCHIECTASIS(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100)) 

INSERT INTO sailw1317v.SS_COPD_BRONCHIECTASIS
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.COPD_BRONCHIECTASIS

SELECT * FROM sailw1317v.SS_COPD_BRONCHIECTASIS


--BMI
DECLARE GLOBAL TEMPORARY TABLE COPD_BMI AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_BMI cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_COPD SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_COPD_BMI

-- Create perminent table 
CREATE TABLE sailw1317v.SS_COPD_BMI(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_COPD_BMI
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.COPD_BMI

SELECT * FROM sailw1317v.SS_COPD_BMI

-- CHD
DECLARE GLOBAL TEMPORARY TABLE COPD_CHD AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_CHD cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_COPD SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_COPD_CHD

-- Create perminent table 
CREATE TABLE sailw1317v.SS_COPD_CHD(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_COPD_CHD
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.COPD_CHD

SELECT * FROM sailw1317v.SS_COPD_CHD

--DIABETES
DECLARE GLOBAL TEMPORARY TABLE COPD_DIABETES AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_DIABETES cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_COPD SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_COPD_DIABETES

-- Create perminent table 
CREATE TABLE sailw1317v.SS_COPD_DIABETES(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_COPD_DIABETES
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.COPD_DIABETES

SELECT * FROM sailw1317v.SS_COPD_DIABETES

-- DEPRESSION 
DECLARE GLOBAL TEMPORARY TABLE COPD_DEPRESSION AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_DEPRESSION cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_COPD SSA ON wgec.ALF_PE = SSA.ALF_PE
WHERE wgec.EVENT_CD NOT IN ( '68910', '8IH31', '6891.', '6896.', 'ZV790' )
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_COPD_DEPRESSION

-- Create perminent table 
CREATE TABLE sailw1317v.SS_COPD_DEPRESSION(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100)) 

INSERT INTO sailw1317v.SS_COPD_DEPRESSION
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.COPD_DEPRESSION

SELECT * FROM sailw1317v.SS_COPD_DEPRESSION

--HEART_FAILURE
DECLARE GLOBAL TEMPORARY TABLE COPD_HEART_FAILURE AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_HEART_FAILURE cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_COPD SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_COPD_HEART_FAILURE

-- Create perminent table 
CREATE TABLE sailw1317v.SS_COPD_HEART_FAILURE( 
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_COPD_HEART_FAILURE 
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.COPD_HEART_FAILURE 

SELECT * FROM sailw1317v.SS_COPD_HEART_FAILURE 

-- HYPERTENSION
DECLARE GLOBAL TEMPORARY TABLE COPD_HYPERTENSION AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN  SAILW1317V.CM_HYPERTENSION cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_COPD SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_COPD_HYPERTENSION

-- Create perminent table 
CREATE TABLE sailw1317v.SS_COPD_HYPERTENSION(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100)) 

INSERT INTO sailw1317v.SS_COPD_HYPERTENSION 
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.COPD_HYPERTENSION 

SELECT * FROM sailw1317v.SS_COPD_HYPERTENSION 

--LEARNING_DISABILITY
DECLARE GLOBAL TEMPORARY TABLE COPD_LEARNING_DISABILITY AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_LEARNING_DISABILITY cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_COPD SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_COPD_LEARNING_DISABILITY

-- Create perminent table 
CREATE TABLE sailw1317v.SS_COPD_LEARNING_DISABILITY(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_COPD_LEARNING_DISABILITY
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.COPD_LEARNING_DISABILITY

SELECT * FROM sailw1317v.SS_COPD_LEARNING_DISABILITY

--LUNG_CANCER
DECLARE GLOBAL TEMPORARY TABLE COPD_LUNG_CANCER AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_LUNG_CANCER cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_COPD SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_COPD_LUNG_CANCER

-- Create perminent table 
CREATE TABLE sailw1317v.SS_COPD_LUNG_CANCER( 
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_COPD_LUNG_CANCER 
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.COPD_LUNG_CANCER 

SELECT * FROM sailw1317v.SS_COPD_LUNG_CANCER 

--OSTEOPOROSIS
DECLARE GLOBAL TEMPORARY TABLE COPD_OSTEOPOROSIS AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_OSTEOPOROSIS cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_COPD SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_COPD_OSTEOPOROSIS

-- Create perminent table 
CREATE TABLE sailw1317v.SS_COPD_OSTEOPOROSIS(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100))

INSERT INTO sailw1317v.SS_COPD_OSTEOPOROSIS
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.COPD_OSTEOPOROSIS

SELECT * FROM sailw1317v.SS_COPD_OSTEOPOROSIS

--SMI
DECLARE GLOBAL TEMPORARY TABLE COPD_SMI AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD,  wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_SMI cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_COPD SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_COPD_SMI

-- Create perminent table 
CREATE TABLE sailw1317v.SS_COPD_SMI(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100)) 

INSERT INTO sailw1317v.SS_COPD_SMI
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.COPD_SMI

SELECT * FROM sailw1317v.SS_COPD_SMI

--STROKE
DECLARE GLOBAL TEMPORARY TABLE COPD_STROKE AS ( SELECT wgec.ALF_PE, wgec.EVENT_CD, wgec.EVENT_DT, SSA.AGE_AT_END_OF_FOLLOW_UP, wgec.GNDR_CD, SSA.GP_PRACTICE_CLUSTER_CODE , SSA.GP_PRACTICE_CLUSTER_NAME, wgec.PRAC_CD_PE 
FROM SAIL1317V.WLGP_GP_EVENT_CLEANSED_20211101 wgec 
INNER JOIN SAILW1317V.CM_STROKE cc ON cc.EVENT_CD = wgec.EVENT_CD
INNER JOIN sailw1317v.SS_COPD SSA ON wgec.ALF_PE = SSA.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DROP TABLE sailw1317v.SS_COPD_STROKE

-- Create perminent table 
CREATE TABLE sailw1317v.SS_COPD_STROKE(
ALF_PE VARCHAR (100)
, EVENT_CD VARCHAR (100)
, EVENT_DT DATE
, AGE_AT_END_OF_FOLLOW_UP VARCHAR (100)
, GNDR_CD VARCHAR (100)
, GP_PRACTICE_CLUSTER_CODE VARCHAR (100) 
, GP_PRACTICE_CLUSTER_NAME VARCHAR (100)
, PRAC_CD_PE VARCHAR (100)) 

INSERT INTO sailw1317v.SS_COPD_STROKE
SELECT ALF_PE
, EVENT_CD
, EVENT_DT
, AGE_AT_END_OF_FOLLOW_UP
, GNDR_CD
, GP_PRACTICE_CLUSTER_CODE 
, GP_PRACTICE_CLUSTER_NAME
, PRAC_CD_PE 
FROM SESSION.COPD_STROKE

SELECT * FROM sailw1317v.SS_COPD_STROKE



